package cardgen

import (
	"fmt"
	"strings"

	"github.com/natefinch/council4/mtg/game"
)

// enumLiteral returns the Go expression naming v in generated card source.
//
// literals is a table generated by cardgen/cmd/genrender covering every exported
// constant of v's type, so a lookup miss means v is not a declared constant of
// that type — a lowering bug rather than a renderer gap. Before these tables the
// mappings were written by hand and covered only the constants someone had
// needed so far, so a lowering that produced a perfectly valid constant (half of
// game.Step, zone.Stack, game.ResolutionChoiceCardName) failed to render and the
// card was dropped.
//
// kind names the value's type in the error message.
func enumLiteral[T comparable](literals map[T]string, kind string, v T) (string, error) {
	literal, ok := literals[v]
	if !ok {
		return "", fmt.Errorf("render: %s %v is not a declared constant", kind, v)
	}
	return literal, nil
}

// enumLiteralNonZero is enumLiteral for types whose zero value means "this field
// is not set" rather than naming a real value. Emitting such a constant into a
// field would assert something the value does not say, so reaching one here is a
// lowering bug and fails closed.
//
// Which types these are is genuine per-type semantics, not a pattern: zone.None
// means no zone, but game.DurationPermanent is the zero EffectDuration and is
// also a real duration that renders normally.
func enumLiteralNonZero[T comparable](literals map[T]string, kind string, v T) (string, error) {
	var zero T
	if v == zero {
		return "", fmt.Errorf("render: %s is unset and names no value", kind)
	}
	return enumLiteral(literals, kind, v)
}

// unrenderedEventKinds are game.EventKind values that are deliberately not
// emitted into generated source. They are produced and consumed only by runtime
// machinery (replacement effects, copies, phasing, reveals, dungeon and
// initiative bookkeeping), so no card's text lowers to a trigger on them and
// failing closed keeps a lowering bug from generating a trigger that never
// fires.
//
// This is the one exclusion set the renderer keeps. Every other former gap was
// an incomplete hand-written table rather than a deliberate exclusion.
var unrenderedEventKinds = map[game.EventKind]bool{
	game.EventSpellResolved:       true,
	game.EventDamagePrevented:     true,
	game.EventDestroyReplaced:     true,
	game.EventCardRevealed:        true,
	game.EventSpellCopied:         true,
	game.EventPermanentPhasedOut:  true,
	game.EventPermanentPhasedIn:   true,
	game.EventVenturedIntoDungeon: true,
	game.EventTookInitiative:      true,
}

// bitmaskValue constrains the integer kinds the flag-shaped game enums use.
type bitmaskValue interface {
	~int | ~int8 | ~int16 | ~int32 | ~int64 | ~uint | ~uint8 | ~uint16 | ~uint32 | ~uint64
}

// enumFlag pairs one flag of a bitmask type with the Go expression naming it.
type enumFlag[T bitmaskValue] struct {
	Flag    T
	Literal string
}

// bitmaskLiteral returns the Go expression naming v as an OR of the flags it
// sets, in the order genrender emitted them.
//
// flags covers every declared flag of v's type, so a leftover bit means v sets
// something that is not a declared flag. Callers decide what the zero value
// means: it may be a legitimate "unspecified" literal or an error, so
// bitmaskLiteral reports it as no flags set and leaves the choice to them.
func bitmaskLiteral[T bitmaskValue](flags []enumFlag[T], kind string, v T) (string, error) {
	var (
		set       []string
		remaining = v
	)
	for _, f := range flags {
		if v&f.Flag != 0 {
			set = append(set, f.Literal)
			remaining &^= f.Flag
		}
	}
	if remaining != 0 {
		return "", fmt.Errorf("render: %s %d sets bits that are not declared flags", kind, v)
	}
	return strings.Join(set, " | "), nil
}
