package cardgen

import (
	"fmt"
	"strconv"
	"strings"

	"github.com/natefinch/council4/mtg/game"
	"github.com/natefinch/council4/mtg/game/color"
)

// enumLiteral returns the Go expression naming v in generated card source.
//
// literals is a table generated by cardgen/cmd/genrender covering every exported
// constant of v's type, so a lookup miss means v is not a declared constant of
// that type — a lowering bug rather than a renderer gap. Before these tables the
// mappings were written by hand and covered only the constants someone had
// needed so far, so a lowering that produced a perfectly valid constant (half of
// game.Step, zone.Stack, game.ResolutionChoiceCardName) failed to render and the
// card was dropped.
//
// kind names the value's type in the error message.
func enumLiteral[T comparable](literals map[T]string, kind string, v T) (string, error) {
	literal, ok := literals[v]
	if !ok {
		return "", fmt.Errorf("render: %s %v is not a declared constant", kind, v)
	}
	return literal, nil
}

// enumLiteralNonZero is enumLiteral for types whose zero value means "this field
// is not set" rather than naming a real value. Emitting such a constant into a
// field would assert something the value does not say, so reaching one here is a
// lowering bug and fails closed.
//
// Which types these are is genuine per-type semantics, not a pattern: zone.None
// means no zone, but game.DurationPermanent is the zero EffectDuration and is
// also a real duration that renders normally.
func enumLiteralNonZero[T comparable](literals map[T]string, kind string, v T) (string, error) {
	var zero T
	if v == zero {
		return "", fmt.Errorf("render: %s is unset and names no value", kind)
	}
	return enumLiteral(literals, kind, v)
}

// unrenderedEventKinds are game.EventKind values that are deliberately not
// emitted into generated source. They are produced and consumed only by runtime
// machinery (replacement effects, copies, phasing, reveals, dungeon and
// initiative bookkeeping), so no card's text lowers to a trigger on them and
// failing closed keeps a lowering bug from generating a trigger that never
// fires.
//
// This is the one exclusion set the renderer keeps. Every other former gap was
// an incomplete hand-written table rather than a deliberate exclusion.
var unrenderedEventKinds = map[game.EventKind]bool{
	game.EventSpellResolved:       true,
	game.EventDamagePrevented:     true,
	game.EventDestroyReplaced:     true,
	game.EventCardRevealed:        true,
	game.EventSpellCopied:         true,
	game.EventPermanentPhasedOut:  true,
	game.EventPermanentPhasedIn:   true,
	game.EventVenturedIntoDungeon: true,
	game.EventTookInitiative:      true,
}

// bitmaskValue constrains the integer kinds the flag-shaped game enums use.
type bitmaskValue interface {
	~int | ~int8 | ~int16 | ~int32 | ~int64 | ~uint | ~uint8 | ~uint16 | ~uint32 | ~uint64
}

// enumFlag pairs one flag of a bitmask type with the Go expression naming it.
type enumFlag[T bitmaskValue] struct {
	Flag    T
	Literal string
}

// bitmaskLiteral returns the Go expression naming v as an OR of the flags it
// sets, in the order genrender emitted them.
//
// flags covers every declared flag of v's type, so a leftover bit means v sets
// something that is not a declared flag. Callers decide what the zero value
// means: it may be a legitimate "unspecified" literal or an error, so
// bitmaskLiteral reports it as no flags set and leaves the choice to them.
func bitmaskLiteral[T bitmaskValue](flags []enumFlag[T], kind string, v T) (string, error) {
	var (
		set       []string
		remaining = v
	)
	for _, f := range flags {
		if v&f.Flag != 0 {
			set = append(set, f.Literal)
			remaining &^= f.Flag
		}
	}
	if remaining != 0 {
		return "", fmt.Errorf("render: %s %d sets bits that are not declared flags", kind, v)
	}
	return strings.Join(set, " | "), nil
}

// renderColorIdentity renders a color.Identity as the constructor call that
// rebuilds it. Identity keeps its colors in unexported state, so it cannot be
// written as a composite literal from this package.
func (Renderer) renderColorIdentity(ctx *renderCtx, identity color.Identity) (string, error) {
	cols := identity.Colors()
	if len(cols) == 0 {
		return "color.Identity{}", nil
	}
	ctx.need(importColor)
	lits, err := colorValueLiterals(cols)
	if err != nil {
		return "", err
	}
	return "color.NewIdentity(" + lits + ")", nil
}

// compactSliceLit renders a slice literal on a single line, for use inside a
// struct literal that must itself stay inline.
func compactSliceLit(elementType string, elements []string) string {
	return "[]" + elementType + "{" + strings.Join(elements, ", ") + "}"
}

// namedSliceLit renders a slice literal. A defined slice type such as cost.Mana
// spells its literal with that name; an unnamed slice spells it with the element
// type, as []T.
func namedSliceLit(namedType, elementType string, elements []string) string {
	if namedType == "" {
		return sliceLit(elementType, elements)
	}
	if len(elements) == 0 {
		return namedType + "{}"
	}
	return namedType + "{\n" + strings.Join(elements, "\n") + "\n}"
}

// compactNamedSliceLit is namedSliceLit on a single line, for use inside a
// struct literal that must stay inline.
func compactNamedSliceLit(namedType, elementType string, elements []string) string {
	if namedType == "" {
		return compactSliceLit(elementType, elements)
	}
	return namedType + "{" + strings.Join(elements, ", ") + "}"
}

// pointerLit renders a pointer to a value whose literal is a constructor call.
// Go has no address-of for a call result, so the value is bound to a local
// inside an immediately-called function literal.
func pointerLit(typeName, valueLit string) string {
	return "func() *" + typeName + " { ref := " + valueLit + "; return &ref }()"
}

// openStringLiteral renders a value of a named string type that has exported
// constants but is not a closed set, such as game.ChoiceKey.
//
// A constant name is used when one names the value, because that is what the
// generated card should say; anything else is a conversion of the literal
// string. Unlike enumLiteral this cannot fail: lowering synthesizes keys such as
// "oracle-mana-color" that no constant names, and those are routine rather than
// a bug.
func openStringLiteral[T ~string](literals map[T]string, kind string, v T) (string, error) {
	if literal, ok := literals[v]; ok {
		return literal, nil
	}
	return kind + "(" + strconv.Quote(string(v)) + ")", nil
}

// flagsSpelling names a bitmask value for enumSpelling, reporting false when the
// value sets an undeclared bit.
//
// The zero value names no flags, which reads as an empty spelling rather than an
// error: for a bitmask, "nothing set" is a legitimate state.
func flagsSpelling[T bitmaskValue](v T, flags []enumFlag[T]) (string, bool) {
	spelling, err := bitmaskLiteral(flags, "flags", v)
	if err != nil {
		return "", false
	}
	return spelling, true
}
