// Code generated by cardgen/cmd/genrender. DO NOT EDIT.

package cardgen

import (
	"github.com/natefinch/council4/mtg/game"
	"github.com/natefinch/council4/mtg/game/color"
	"github.com/natefinch/council4/mtg/game/compare"
	"github.com/natefinch/council4/mtg/game/cost"
	"github.com/natefinch/council4/mtg/game/counter"
	"github.com/natefinch/council4/mtg/game/mana"
	"github.com/natefinch/council4/mtg/game/types"
	"github.com/natefinch/council4/mtg/game/zone"
)

// colorColorLiterals maps each exported color.Color constant to the Go
// expression that names it in generated card source.
var colorColorLiterals = map[color.Color]string{
	color.White: "color.White",
	color.Blue:  "color.Blue",
	color.Black: "color.Black",
	color.Red:   "color.Red",
	color.Green: "color.Green",
}

// compareOpLiterals maps each exported compare.Op constant to the Go
// expression that names it in generated card source.
var compareOpLiterals = map[compare.Op]string{
	compare.Any:            "compare.Any",
	compare.Equal:          "compare.Equal",
	compare.LessOrEqual:    "compare.LessOrEqual",
	compare.GreaterOrEqual: "compare.GreaterOrEqual",
	compare.LessThan:       "compare.LessThan",
	compare.GreaterThan:    "compare.GreaterThan",
}

// costAdditionalDynamicAmountLiterals maps each exported cost.AdditionalDynamicAmount constant to the Go
// expression that names it in generated card source.
var costAdditionalDynamicAmountLiterals = map[cost.AdditionalDynamicAmount]string{
	cost.AdditionalDynamicAmountNone:                  "cost.AdditionalDynamicAmountNone",
	cost.AdditionalDynamicCommanderColorIdentityCount: "cost.AdditionalDynamicCommanderColorIdentityCount",
	cost.AdditionalDynamicHandSize:                    "cost.AdditionalDynamicHandSize",
	cost.AdditionalDynamicLifeGainedThisTurn:          "cost.AdditionalDynamicLifeGainedThisTurn",
}

// costAdditionalKindLiterals maps each exported cost.AdditionalKind constant to the Go
// expression that names it in generated card source.
var costAdditionalKindLiterals = map[cost.AdditionalKind]string{
	cost.AdditionalUnknown:                 "cost.AdditionalUnknown",
	cost.AdditionalSacrifice:               "cost.AdditionalSacrifice",
	cost.AdditionalSacrificeSource:         "cost.AdditionalSacrificeSource",
	cost.AdditionalDiscard:                 "cost.AdditionalDiscard",
	cost.AdditionalPayLife:                 "cost.AdditionalPayLife",
	cost.AdditionalExile:                   "cost.AdditionalExile",
	cost.AdditionalReveal:                  "cost.AdditionalReveal",
	cost.AdditionalTap:                     "cost.AdditionalTap",
	cost.AdditionalExileSource:             "cost.AdditionalExileSource",
	cost.AdditionalUntap:                   "cost.AdditionalUntap",
	cost.AdditionalRemoveCounter:           "cost.AdditionalRemoveCounter",
	cost.AdditionalReturnUnblockedAttacker: "cost.AdditionalReturnUnblockedAttacker",
	cost.AdditionalTapPermanents:           "cost.AdditionalTapPermanents",
	cost.AdditionalEnergy:                  "cost.AdditionalEnergy",
	cost.AdditionalReturnToHand:            "cost.AdditionalReturnToHand",
	cost.AdditionalExert:                   "cost.AdditionalExert",
	cost.AdditionalMill:                    "cost.AdditionalMill",
	cost.AdditionalPutCounter:              "cost.AdditionalPutCounter",
	cost.AdditionalCollectEvidence:         "cost.AdditionalCollectEvidence",
	cost.AdditionalRemoveCounterAmong:      "cost.AdditionalRemoveCounterAmong",
}

// costAlternativeConditionLiterals maps each exported cost.AlternativeCondition constant to the Go
// expression that names it in generated card source.
var costAlternativeConditionLiterals = map[cost.AlternativeCondition]string{
	cost.AlternativeConditionNone:                       "cost.AlternativeConditionNone",
	cost.AlternativeConditionControlsCommander:          "cost.AlternativeConditionControlsCommander",
	cost.AlternativeConditionNotYourTurn:                "cost.AlternativeConditionNotYourTurn",
	cost.AlternativeConditionOpponentLostLifeThisTurn:   "cost.AlternativeConditionOpponentLostLifeThisTurn",
	cost.AlternativeConditionYourTurn:                   "cost.AlternativeConditionYourTurn",
	cost.AlternativeConditionControlsPermanentSubtype:   "cost.AlternativeConditionControlsPermanentSubtype",
	cost.AlternativeConditionOpponentGainedLifeThisTurn: "cost.AlternativeConditionOpponentGainedLifeThisTurn",
	cost.AlternativeConditionCreaturesAttacking:         "cost.AlternativeConditionCreaturesAttacking",
	cost.AlternativeConditionPermanentsOnBattlefield:    "cost.AlternativeConditionPermanentsOnBattlefield",
	cost.AlternativeConditionOpponentCastSpellsThisTurn: "cost.AlternativeConditionOpponentCastSpellsThisTurn",
}

// costAlternativeMechanicLiterals maps each exported cost.AlternativeMechanic constant to the Go
// expression that names it in generated card source.
var costAlternativeMechanicLiterals = map[cost.AlternativeMechanic]string{
	cost.AlternativeMechanicNone:                "cost.AlternativeMechanicNone",
	cost.AlternativeMechanicFlashback:           "cost.AlternativeMechanicFlashback",
	cost.AlternativeMechanicEscape:              "cost.AlternativeMechanicEscape",
	cost.AlternativeMechanicEvoke:               "cost.AlternativeMechanicEvoke",
	cost.AlternativeMechanicMoreThanMeetsTheEye: "cost.AlternativeMechanicMoreThanMeetsTheEye",
	cost.AlternativeMechanicDash:                "cost.AlternativeMechanicDash",
}

// costPowerContributionKindLiterals maps each exported cost.PowerContributionKind constant to the Go
// expression that names it in generated card source.
var costPowerContributionKindLiterals = map[cost.PowerContributionKind]string{
	cost.PowerContributionEffective: "cost.PowerContributionEffective",
	cost.PowerContributionCrew:      "cost.PowerContributionCrew",
}

// costSymbolKindLiterals maps each exported cost.SymbolKind constant to the Go
// expression that names it in generated card source.
var costSymbolKindLiterals = map[cost.SymbolKind]string{
	cost.ColoredSymbol:          "cost.ColoredSymbol",
	cost.GenericSymbol:          "cost.GenericSymbol",
	cost.ColorlessSymbol:        "cost.ColorlessSymbol",
	cost.VariableSymbol:         "cost.VariableSymbol",
	cost.HybridSymbol:           "cost.HybridSymbol",
	cost.TwobridSymbol:          "cost.TwobridSymbol",
	cost.PhyrexianSymbol:        "cost.PhyrexianSymbol",
	cost.SnowSymbol:             "cost.SnowSymbol",
	cost.PhyrexianGenericSymbol: "cost.PhyrexianGenericSymbol",
}

// counterKindLiterals maps each exported counter.Kind constant to the Go
// expression that names it in generated card source.
var counterKindLiterals = map[counter.Kind]string{
	counter.PlusOnePlusOne:    "counter.PlusOnePlusOne",
	counter.MinusOneMinusOne:  "counter.MinusOneMinusOne",
	counter.Loyalty:           "counter.Loyalty",
	counter.Charge:            "counter.Charge",
	counter.Time:              "counter.Time",
	counter.Defense:           "counter.Defense",
	counter.Poison:            "counter.Poison",
	counter.Lore:              "counter.Lore",
	counter.Verse:             "counter.Verse",
	counter.Shield:            "counter.Shield",
	counter.Stun:              "counter.Stun",
	counter.Finality:          "counter.Finality",
	counter.Brick:             "counter.Brick",
	counter.Page:              "counter.Page",
	counter.Enlightened:       "counter.Enlightened",
	counter.Oil:               "counter.Oil",
	counter.Blood:             "counter.Blood",
	counter.Indestructible:    "counter.Indestructible",
	counter.Deathtouch:        "counter.Deathtouch",
	counter.Flying:            "counter.Flying",
	counter.FirstStrike:       "counter.FirstStrike",
	counter.Hexproof:          "counter.Hexproof",
	counter.Lifelink:          "counter.Lifelink",
	counter.Menace:            "counter.Menace",
	counter.Reach:             "counter.Reach",
	counter.Trample:           "counter.Trample",
	counter.Vigilance:         "counter.Vigilance",
	counter.Energy:            "counter.Energy",
	counter.Experience:        "counter.Experience",
	counter.Burden:            "counter.Burden",
	counter.Age:               "counter.Age",
	counter.Quest:             "counter.Quest",
	counter.Level:             "counter.Level",
	counter.PlusOnePlusZero:   "counter.PlusOnePlusZero",
	counter.PlusTwoPlusTwo:    "counter.PlusTwoPlusTwo",
	counter.MinusZeroMinusOne: "counter.MinusZeroMinusOne",
	counter.PlusZeroPlusOne:   "counter.PlusZeroPlusOne",
	counter.MinusZeroMinusTwo: "counter.MinusZeroMinusTwo",
	counter.MinusTwoMinusTwo:  "counter.MinusTwoMinusTwo",
	counter.PlusOnePlusTwo:    "counter.PlusOnePlusTwo",
	counter.PlusZeroPlusTwo:   "counter.PlusZeroPlusTwo",
	counter.MinusTwoMinusOne:  "counter.MinusTwoMinusOne",
	counter.MinusOneMinusZero: "counter.MinusOneMinusZero",
	counter.Spore:             "counter.Spore",
	counter.Fade:              "counter.Fade",
	counter.Divinity:          "counter.Divinity",
	counter.Healing:           "counter.Healing",
	counter.Wish:              "counter.Wish",
	counter.Study:             "counter.Study",
	counter.Dream:             "counter.Dream",
	counter.Supply:            "counter.Supply",
	counter.Story:             "counter.Story",
	counter.Film:              "counter.Film",
	counter.Hoofprint:         "counter.Hoofprint",
	counter.Suspect:           "counter.Suspect",
	counter.Javelin:           "counter.Javelin",
	counter.Cube:              "counter.Cube",
	counter.Polyp:             "counter.Polyp",
	counter.Component:         "counter.Component",
	counter.Eon:               "counter.Eon",
	counter.Incubation:        "counter.Incubation",
	counter.Devotion:          "counter.Devotion",
	counter.Foreshadow:        "counter.Foreshadow",
	counter.Arrowhead:         "counter.Arrowhead",
	counter.Carrion:           "counter.Carrion",
	counter.Corpse:            "counter.Corpse",
	counter.Loot:              "counter.Loot",
	counter.Net:               "counter.Net",
	counter.Gold:              "counter.Gold",
	counter.Currency:          "counter.Currency",
	counter.Book:              "counter.Book",
	counter.Blaze:             "counter.Blaze",
	counter.Palliation:        "counter.Palliation",
	counter.Gem:               "counter.Gem",
	counter.Pressure:          "counter.Pressure",
	counter.Flame:             "counter.Flame",
	counter.Ice:               "counter.Ice",
	counter.Coin:              "counter.Coin",
	counter.Depletion:         "counter.Depletion",
	counter.Croak:             "counter.Croak",
	counter.Void:              "counter.Void",
	counter.Intel:             "counter.Intel",
	counter.Collection:        "counter.Collection",
	counter.Hour:              "counter.Hour",
	counter.Ribbon:            "counter.Ribbon",
}

// gameAggregateKindLiterals maps each exported game.AggregateKind constant to the Go
// expression that names it in generated card source.
var gameAggregateKindLiterals = map[game.AggregateKind]string{
	game.AggregateNone:                                   "game.AggregateNone",
	game.AggregateControllerLife:                         "game.AggregateControllerLife",
	game.AggregateControllerLifeAboveStarting:            "game.AggregateControllerLifeAboveStarting",
	game.AggregateControllerHandSize:                     "game.AggregateControllerHandSize",
	game.AggregateControllerLibrarySize:                  "game.AggregateControllerLibrarySize",
	game.AggregateControllerGraveyardCardCount:           "game.AggregateControllerGraveyardCardCount",
	game.AggregateControllerGraveyardCardTypeCount:       "game.AggregateControllerGraveyardCardTypeCount",
	game.AggregateControllerBasicLandTypeCount:           "game.AggregateControllerBasicLandTypeCount",
	game.AggregateControllerCreaturePowerDiversity:       "game.AggregateControllerCreaturePowerDiversity",
	game.AggregateOpponentCount:                          "game.AggregateOpponentCount",
	game.AggregateAttackersAttackingController:           "game.AggregateAttackersAttackingController",
	game.AggregateControllerGainedLifeThisTurn:           "game.AggregateControllerGainedLifeThisTurn",
	game.AggregateSpellX:                                 "game.AggregateSpellX",
	game.AggregateControllerGraveyardPermanentCardCount:  "game.AggregateControllerGraveyardPermanentCardCount",
	game.AggregateControllerGraveyardManaValueCount:      "game.AggregateControllerGraveyardManaValueCount",
	game.AggregateAnyOpponentGraveyardCardCount:          "game.AggregateAnyOpponentGraveyardCardCount",
	game.AggregateEventSpellManaSpentToCast:              "game.AggregateEventSpellManaSpentToCast",
	game.AggregateEventPlayerHandSize:                    "game.AggregateEventPlayerHandSize",
	game.AggregateAnyOpponentDamageTakenThisTurn:         "game.AggregateAnyOpponentDamageTakenThisTurn",
	game.AggregateMinPlayerLibrarySize:                   "game.AggregateMinPlayerLibrarySize",
	game.AggregateAnyOpponentLifeLostThisTurn:            "game.AggregateAnyOpponentLifeLostThisTurn",
	game.AggregateAttackersInBatchAttackedController:     "game.AggregateAttackersInBatchAttackedController",
	game.AggregateEventSpellManaFromCreaturesSpentToCast: "game.AggregateEventSpellManaFromCreaturesSpentToCast",
	game.AggregateControllerDevotion:                     "game.AggregateControllerDevotion",
	game.AggregateEventPermanentCastX:                    "game.AggregateEventPermanentCastX",
}

// gameAttackRecipientKindFlags lists every exported game.AttackRecipientKind flag in ascending
// value order, which is the order set flags are ORed together in generated
// card source.
var gameAttackRecipientKindFlags = []enumFlag[game.AttackRecipientKind]{
	{Flag: game.AttackRecipientPlayer, Literal: "game.AttackRecipientPlayer"},
	{Flag: game.AttackRecipientPlaneswalker, Literal: "game.AttackRecipientPlaneswalker"},
	{Flag: game.AttackRecipientBattle, Literal: "game.AttackRecipientBattle"},
}

// gameBlockerRestrictionKindLiterals maps each exported game.BlockerRestrictionKind constant to the Go
// expression that names it in generated card source.
var gameBlockerRestrictionKindLiterals = map[game.BlockerRestrictionKind]string{
	game.BlockerRestrictionNone:                "game.BlockerRestrictionNone",
	game.BlockerRestrictionFlying:              "game.BlockerRestrictionFlying",
	game.BlockerRestrictionFlyingOrReach:       "game.BlockerRestrictionFlyingOrReach",
	game.BlockerRestrictionPowerLessOrEqual:    "game.BlockerRestrictionPowerLessOrEqual",
	game.BlockerRestrictionPowerGreaterOrEqual: "game.BlockerRestrictionPowerGreaterOrEqual",
	game.BlockerRestrictionColor:               "game.BlockerRestrictionColor",
	game.BlockerRestrictionArtifact:            "game.BlockerRestrictionArtifact",
	game.BlockerRestrictionDefender:            "game.BlockerRestrictionDefender",
	game.BlockerRestrictionLegendary:           "game.BlockerRestrictionLegendary",
	game.BlockerRestrictionControlledByMonarch: "game.BlockerRestrictionControlledByMonarch",
}

// gameCardLayoutLiterals maps each exported game.CardLayout constant to the Go
// expression that names it in generated card source.
var gameCardLayoutLiterals = map[game.CardLayout]string{
	game.LayoutNormal:           "game.LayoutNormal",
	game.LayoutTransform:        "game.LayoutTransform",
	game.LayoutModalDFC:         "game.LayoutModalDFC",
	game.LayoutMeld:             "game.LayoutMeld",
	game.LayoutDoubleFacedToken: "game.LayoutDoubleFacedToken",
	game.LayoutReversibleCard:   "game.LayoutReversibleCard",
	game.LayoutAdventure:        "game.LayoutAdventure",
	game.LayoutSplit:            "game.LayoutSplit",
	game.LayoutPrepare:          "game.LayoutPrepare",
}

// gameCardReferenceKindLiterals maps each exported game.CardReferenceKind constant to the Go
// expression that names it in generated card source.
var gameCardReferenceKindLiterals = map[game.CardReferenceKind]string{
	game.CardReferenceNone:     "game.CardReferenceNone",
	game.CardReferenceLinked:   "game.CardReferenceLinked",
	game.CardReferenceSource:   "game.CardReferenceSource",
	game.CardReferenceEvent:    "game.CardReferenceEvent",
	game.CardReferenceTarget:   "game.CardReferenceTarget",
	game.CardReferenceCaptured: "game.CardReferenceCaptured",
}

// gameChoiceKeyLiterals maps each exported game.ChoiceKey constant to the Go
// expression that names it in generated card source.
var gameChoiceKeyLiterals = map[game.ChoiceKey]string{
	game.EntryTypeChoiceKey:                 "game.EntryTypeChoiceKey",
	game.EntryCardTypeChoiceKey:             "game.EntryCardTypeChoiceKey",
	game.EntryColorChoiceKey:                "game.EntryColorChoiceKey",
	game.AttachmentCardNameChoiceKey:        "game.AttachmentCardNameChoiceKey",
	game.AttachmentSubtypeChoiceKey:         "game.AttachmentSubtypeChoiceKey",
	game.SpellChosenTypeChoiceKey:           "game.SpellChosenTypeChoiceKey",
	game.ResolutionChosenPermanentChoiceKey: "game.ResolutionChosenPermanentChoiceKey",
}

// gameChooseCountLiterals maps each exported game.ChooseCount constant to the Go
// expression that names it in generated card source.
var gameChooseCountLiterals = map[game.ChooseCount]string{
	game.ChooseExactly:   "game.ChooseExactly",
	game.ChooseUpTo:      "game.ChooseUpTo",
	game.ChooseAnyNumber: "game.ChooseAnyNumber",
}

// gameChooseGroupingLiterals maps each exported game.ChooseGrouping constant to the Go
// expression that names it in generated card source.
var gameChooseGroupingLiterals = map[game.ChooseGrouping]string{
	game.ChooseAcrossSet:          "game.ChooseAcrossSet",
	game.ChooseOneOfEachNamedType: "game.ChooseOneOfEachNamedType",
	game.ChooseSplitDestination:   "game.ChooseSplitDestination",
	game.ChooseSharedSubtype:      "game.ChooseSharedSubtype",
}

// gameChoosePositionLiterals maps each exported game.ChoosePosition constant to the Go
// expression that names it in generated card source.
var gameChoosePositionLiterals = map[game.ChoosePosition]string{
	game.ChoosePositionDefault: "game.ChoosePositionDefault",
	game.ChoosePositionTop:     "game.ChoosePositionTop",
}

// gameColorChoiceSourceLiterals maps each exported game.ColorChoiceSource constant to the Go
// expression that names it in generated card source.
var gameColorChoiceSourceLiterals = map[game.ColorChoiceSource]string{
	game.ColorChoiceNone:        "game.ColorChoiceNone",
	game.ColorChoiceSourceEntry: "game.ColorChoiceSourceEntry",
}

// gameCombatStateFilterLiterals maps each exported game.CombatStateFilter constant to the Go
// expression that names it in generated card source.
var gameCombatStateFilterLiterals = map[game.CombatStateFilter]string{
	game.CombatStateAny:                 "game.CombatStateAny",
	game.CombatStateAttacking:           "game.CombatStateAttacking",
	game.CombatStateBlocking:            "game.CombatStateBlocking",
	game.CombatStateAttackingOrBlocking: "game.CombatStateAttackingOrBlocking",
}

// gameContinuousLayerLiterals maps each exported game.ContinuousLayer constant to the Go
// expression that names it in generated card source.
var gameContinuousLayerLiterals = map[game.ContinuousLayer]string{
	game.LayerCopy:                 "game.LayerCopy",
	game.LayerControl:              "game.LayerControl",
	game.LayerText:                 "game.LayerText",
	game.LayerType:                 "game.LayerType",
	game.LayerColor:                "game.LayerColor",
	game.LayerAbility:              "game.LayerAbility",
	game.LayerPowerToughnessCDA:    "game.LayerPowerToughnessCDA",
	game.LayerPowerToughnessSet:    "game.LayerPowerToughnessSet",
	game.LayerPowerToughnessModify: "game.LayerPowerToughnessModify",
	game.LayerPowerToughnessSwitch: "game.LayerPowerToughnessSwitch",
}

// gameControlPlayerScopeLiterals maps each exported game.ControlPlayerScope constant to the Go
// expression that names it in generated card source.
var gameControlPlayerScopeLiterals = map[game.ControlPlayerScope]string{
	game.ControlPlayerController:       "game.ControlPlayerController",
	game.ControlPlayerAnyOpponent:      "game.ControlPlayerAnyOpponent",
	game.ControlPlayerEachOpponent:     "game.ControlPlayerEachOpponent",
	game.ControlPlayerTriggeringPlayer: "game.ControlPlayerTriggeringPlayer",
}

// gameControllerRelationLiterals maps each exported game.ControllerRelation constant to the Go
// expression that names it in generated card source.
var gameControllerRelationLiterals = map[game.ControllerRelation]string{
	game.ControllerAny:      "game.ControllerAny",
	game.ControllerYou:      "game.ControllerYou",
	game.ControllerOpponent: "game.ControllerOpponent",
	game.ControllerNotYou:   "game.ControllerNotYou",
}

// gameCostModifierKindLiterals maps each exported game.CostModifierKind constant to the Go
// expression that names it in generated card source.
var gameCostModifierKindLiterals = map[game.CostModifierKind]string{
	game.CostModifierSpell:   "game.CostModifierSpell",
	game.CostModifierAbility: "game.CostModifierAbility",
	game.CostModifierAttack:  "game.CostModifierAttack",
}

// gameCounterSourceKindLiterals maps each exported game.CounterSourceKind constant to the Go
// expression that names it in generated card source.
var gameCounterSourceKindLiterals = map[game.CounterSourceKind]string{
	game.CounterSourceNone:           "game.CounterSourceNone",
	game.CounterSourceTarget:         "game.CounterSourceTarget",
	game.CounterSourceEventPermanent: "game.CounterSourceEventPermanent",
	game.CounterSourceSelf:           "game.CounterSourceSelf",
}

// gameCounteredSpellDestinationLiterals maps each exported game.CounteredSpellDestination constant to the Go
// expression that names it in generated card source.
var gameCounteredSpellDestinationLiterals = map[game.CounteredSpellDestination]string{
	game.CounteredSpellGraveyard:  "game.CounteredSpellGraveyard",
	game.CounteredSpellLibraryTop: "game.CounteredSpellLibraryTop",
	game.CounteredSpellHand:       "game.CounteredSpellHand",
}

// gameDamageRecipientKindFlags lists every exported game.DamageRecipientKind flag in ascending
// value order, which is the order set flags are ORed together in generated
// card source.
var gameDamageRecipientKindFlags = []enumFlag[game.DamageRecipientKind]{
	{Flag: game.DamageRecipientPlayer, Literal: "game.DamageRecipientPlayer"},
	{Flag: game.DamageRecipientPermanent, Literal: "game.DamageRecipientPermanent"},
}

// gameDelayedTriggerTimingLiterals maps each exported game.DelayedTriggerTiming constant to the Go
// expression that names it in generated card source.
var gameDelayedTriggerTimingLiterals = map[game.DelayedTriggerTiming]string{
	game.DelayedAtBeginningOfNextEndStep:     "game.DelayedAtBeginningOfNextEndStep",
	game.DelayedAtBeginningOfNextUpkeep:      "game.DelayedAtBeginningOfNextUpkeep",
	game.DelayedAtBeginningOfNextMainPhase:   "game.DelayedAtBeginningOfNextMainPhase",
	game.DelayedAtEndOfCombat:                "game.DelayedAtEndOfCombat",
	game.DelayedAtBeginningOfYourNextEndStep: "game.DelayedAtBeginningOfYourNextEndStep",
}

// gameDelayedTriggerWindowLiterals maps each exported game.DelayedTriggerWindow constant to the Go
// expression that names it in generated card source.
var gameDelayedTriggerWindowLiterals = map[game.DelayedTriggerWindow]string{
	game.DelayedWindowNone:       "game.DelayedWindowNone",
	game.DelayedWindowThisTurn:   "game.DelayedWindowThisTurn",
	game.DelayedWindowUntilFires: "game.DelayedWindowUntilFires",
}

// gameDigRemainderLiterals maps each exported game.DigRemainder constant to the Go
// expression that names it in generated card source.
var gameDigRemainderLiterals = map[game.DigRemainder]string{
	game.DigRemainderGraveyard:     "game.DigRemainderGraveyard",
	game.DigRemainderLibraryBottom: "game.DigRemainderLibraryBottom",
}

// gameDynamicAmountKindLiterals maps each exported game.DynamicAmountKind constant to the Go
// expression that names it in generated card source.
var gameDynamicAmountKindLiterals = map[game.DynamicAmountKind]string{
	game.DynamicAmountNone:                                  "game.DynamicAmountNone",
	game.DynamicAmountConstant:                              "game.DynamicAmountConstant",
	game.DynamicAmountX:                                     "game.DynamicAmountX",
	game.DynamicAmountTargetPower:                           "game.DynamicAmountTargetPower",
	game.DynamicAmountTargetToughness:                       "game.DynamicAmountTargetToughness",
	game.DynamicAmountTargetManaValue:                       "game.DynamicAmountTargetManaValue",
	game.DynamicAmountTargetCounters:                        "game.DynamicAmountTargetCounters",
	game.DynamicAmountControllerLife:                        "game.DynamicAmountControllerLife",
	game.DynamicAmountControllerHandSize:                    "game.DynamicAmountControllerHandSize",
	game.DynamicAmountControllerGraveyardSize:               "game.DynamicAmountControllerGraveyardSize",
	game.DynamicAmountControllerBasicLandTypeCount:          "game.DynamicAmountControllerBasicLandTypeCount",
	game.DynamicAmountCountSelector:                         "game.DynamicAmountCountSelector",
	game.DynamicAmountCountCardsInZone:                      "game.DynamicAmountCountCardsInZone",
	game.DynamicAmountPreviousEffectResult:                  "game.DynamicAmountPreviousEffectResult",
	game.DynamicAmountOpponentCount:                         "game.DynamicAmountOpponentCount",
	game.DynamicAmountEventDamage:                           "game.DynamicAmountEventDamage",
	game.DynamicAmountPreviousEffectExcessDamage:            "game.DynamicAmountPreviousEffectExcessDamage",
	game.DynamicAmountObjectPower:                           "game.DynamicAmountObjectPower",
	game.DynamicAmountEventCardCount:                        "game.DynamicAmountEventCardCount",
	game.DynamicAmountObjectToughness:                       "game.DynamicAmountObjectToughness",
	game.DynamicAmountObjectManaValue:                       "game.DynamicAmountObjectManaValue",
	game.DynamicAmountChosenNumber:                          "game.DynamicAmountChosenNumber",
	game.DynamicAmountObjectCounters:                        "game.DynamicAmountObjectCounters",
	game.DynamicAmountCapturedTargetManaValue:               "game.DynamicAmountCapturedTargetManaValue",
	game.DynamicAmountGreatestPowerInGroup:                  "game.DynamicAmountGreatestPowerInGroup",
	game.DynamicAmountGreatestToughnessInGroup:              "game.DynamicAmountGreatestToughnessInGroup",
	game.DynamicAmountGreatestManaValueInGroup:              "game.DynamicAmountGreatestManaValueInGroup",
	game.DynamicAmountDevotion:                              "game.DynamicAmountDevotion",
	game.DynamicAmountSpellsCastThisTurn:                    "game.DynamicAmountSpellsCastThisTurn",
	game.DynamicAmountEventLifeChange:                       "game.DynamicAmountEventLifeChange",
	game.DynamicAmountTotalPowerInGroup:                     "game.DynamicAmountTotalPowerInGroup",
	game.DynamicAmountTotalToughnessInGroup:                 "game.DynamicAmountTotalToughnessInGroup",
	game.DynamicAmountColorCountInGroup:                     "game.DynamicAmountColorCountInGroup",
	game.DynamicAmountSharedCreatureTypeCountInGroup:        "game.DynamicAmountSharedCreatureTypeCountInGroup",
	game.DynamicAmountSourceCardPower:                       "game.DynamicAmountSourceCardPower",
	game.DynamicAmountBlockingCreaturesBeyondFirst:          "game.DynamicAmountBlockingCreaturesBeyondFirst",
	game.DynamicAmountLifeLostThisTurn:                      "game.DynamicAmountLifeLostThisTurn",
	game.DynamicAmountLifeGainedThisTurn:                    "game.DynamicAmountLifeGainedThisTurn",
	game.DynamicAmountMaxOf:                                 "game.DynamicAmountMaxOf",
	game.DynamicAmountEventCounterCount:                     "game.DynamicAmountEventCounterCount",
	game.DynamicAmountColorsOfManaSpentToCast:               "game.DynamicAmountColorsOfManaSpentToCast",
	game.DynamicAmountTotalManaValueInGroup:                 "game.DynamicAmountTotalManaValueInGroup",
	game.DynamicAmountTimesKicked:                           "game.DynamicAmountTimesKicked",
	game.DynamicAmountOpponentsAttackedThisCombat:           "game.DynamicAmountOpponentsAttackedThisCombat",
	game.DynamicAmountControllerSpeed:                       "game.DynamicAmountControllerSpeed",
	game.DynamicAmountOpponentControllingCount:              "game.DynamicAmountOpponentControllingCount",
	game.DynamicAmountCardsDrawnThisTurn:                    "game.DynamicAmountCardsDrawnThisTurn",
	game.DynamicAmountCardsNamedSourceInGraveyards:          "game.DynamicAmountCardsNamedSourceInGraveyards",
	game.DynamicAmountCardsNamedSourceInControllerGraveyard: "game.DynamicAmountCardsNamedSourceInControllerGraveyard",
	game.DynamicAmountCommanderCastCount:                    "game.DynamicAmountCommanderCastCount",
	game.DynamicAmountBlockingCreatures:                     "game.DynamicAmountBlockingCreatures",
	game.DynamicAmountPlayerLife:                            "game.DynamicAmountPlayerLife",
	game.DynamicAmountSpellTargetCount:                      "game.DynamicAmountSpellTargetCount",
	game.DynamicAmountPartySize:                             "game.DynamicAmountPartySize",
	game.DynamicAmountDamagePreventedThisWay:                "game.DynamicAmountDamagePreventedThisWay",
	game.DynamicAmountTriggeringAttackerCount:               "game.DynamicAmountTriggeringAttackerCount",
	game.DynamicAmountTriggeringEventTotalPower:             "game.DynamicAmountTriggeringEventTotalPower",
	game.DynamicAmountTriggeringEventTotalCombatDamage:      "game.DynamicAmountTriggeringEventTotalCombatDamage",
	game.DynamicAmountReferencedCardsTotalManaValue:         "game.DynamicAmountReferencedCardsTotalManaValue",
}

// gameDynamicValueKindLiterals maps each exported game.DynamicValueKind constant to the Go
// expression that names it in generated card source.
var gameDynamicValueKindLiterals = map[game.DynamicValueKind]string{
	game.DynamicValueNone:                                       "game.DynamicValueNone",
	game.DynamicValueConstant:                                   "game.DynamicValueConstant",
	game.DynamicValueControllerHandSize:                         "game.DynamicValueControllerHandSize",
	game.DynamicValueControllerGraveyardSize:                    "game.DynamicValueControllerGraveyardSize",
	game.DynamicValueControllerCreatureCount:                    "game.DynamicValueControllerCreatureCount",
	game.DynamicValueControllerLandCount:                        "game.DynamicValueControllerLandCount",
	game.DynamicValueControllerArtifactCount:                    "game.DynamicValueControllerArtifactCount",
	game.DynamicValueAllBattlefieldCreatureCount:                "game.DynamicValueAllBattlefieldCreatureCount",
	game.DynamicValueAllGraveyardsSize:                          "game.DynamicValueAllGraveyardsSize",
	game.DynamicValueCreatureCardsInAllGraveyards:               "game.DynamicValueCreatureCardsInAllGraveyards",
	game.DynamicValueCardTypesAmongAllGraveyards:                "game.DynamicValueCardTypesAmongAllGraveyards",
	game.DynamicValueControllerCreatureCardsInGraveyard:         "game.DynamicValueControllerCreatureCardsInGraveyard",
	game.DynamicValueControllerInstantOrSorceryCardsInGraveyard: "game.DynamicValueControllerInstantOrSorceryCardsInGraveyard",
	game.DynamicValueControllerLandCardsInGraveyard:             "game.DynamicValueControllerLandCardsInGraveyard",
	game.DynamicValueControllerCardTypesInGraveyard:             "game.DynamicValueControllerCardTypesInGraveyard",
	game.DynamicValueControllerPermanentCardsInGraveyard:        "game.DynamicValueControllerPermanentCardsInGraveyard",
	game.DynamicValueControllerSubtypeCount:                     "game.DynamicValueControllerSubtypeCount",
	game.DynamicValueControllerBasicLandTypeCount:               "game.DynamicValueControllerBasicLandTypeCount",
	game.DynamicValueControllerLifeTotal:                        "game.DynamicValueControllerLifeTotal",
	game.DynamicValueAllPlayersHandSize:                         "game.DynamicValueAllPlayersHandSize",
	game.DynamicValueControllerColorPermanentCount:              "game.DynamicValueControllerColorPermanentCount",
	game.DynamicValueControllerCardsDrawnThisTurn:               "game.DynamicValueControllerCardsDrawnThisTurn",
	game.DynamicValueSourceLinkedExileCount:                     "game.DynamicValueSourceLinkedExileCount",
}

// gameEffectDurationLiterals maps each exported game.EffectDuration constant to the Go
// expression that names it in generated card source.
var gameEffectDurationLiterals = map[game.EffectDuration]string{
	game.DurationPermanent:                              "game.DurationPermanent",
	game.DurationUntilEndOfTurn:                         "game.DurationUntilEndOfTurn",
	game.DurationThisTurn:                               "game.DurationThisTurn",
	game.DurationUntilYourNextTurn:                      "game.DurationUntilYourNextTurn",
	game.DurationNextTime:                               "game.DurationNextTime",
	game.DurationUntilEndOfYourNextTurn:                 "game.DurationUntilEndOfYourNextTurn",
	game.DurationForAsLongAsSourceOnBattlefield:         "game.DurationForAsLongAsSourceOnBattlefield",
	game.DurationForAsLongAsYouControlSource:            "game.DurationForAsLongAsYouControlSource",
	game.DurationForAsLongAsControlledCreatureEnchanted: "game.DurationForAsLongAsControlledCreatureEnchanted",
	game.DurationUntilYourNextEndStep:                   "game.DurationUntilYourNextEndStep",
	game.DurationUntilEndOfCombat:                       "game.DurationUntilEndOfCombat",
	game.DurationForAsLongAsPlayerIsMonarch:             "game.DurationForAsLongAsPlayerIsMonarch",
}

// gameEffectResultAmountKindLiterals maps each exported game.EffectResultAmountKind constant to the Go
// expression that names it in generated card source.
var gameEffectResultAmountKindLiterals = map[game.EffectResultAmountKind]string{
	game.EffectResultAmountDefault:      "game.EffectResultAmountDefault",
	game.EffectResultAmountExcessDamage: "game.EffectResultAmountExcessDamage",
}

// gameEventHistoryWindowLiterals maps each exported game.EventHistoryWindow constant to the Go
// expression that names it in generated card source.
var gameEventHistoryWindowLiterals = map[game.EventHistoryWindow]string{
	game.EventHistoryCurrentTurn:  "game.EventHistoryCurrentTurn",
	game.EventHistoryPreviousTurn: "game.EventHistoryPreviousTurn",
}

// gameEventKindLiterals maps each exported game.EventKind constant to the Go
// expression that names it in generated card source.
var gameEventKindLiterals = map[game.EventKind]string{
	game.EventUnknown:                     "game.EventUnknown",
	game.EventSpellCast:                   "game.EventSpellCast",
	game.EventSpellResolved:               "game.EventSpellResolved",
	game.EventPermanentEnteredBattlefield: "game.EventPermanentEnteredBattlefield",
	game.EventPermanentDied:               "game.EventPermanentDied",
	game.EventCountersAdded:               "game.EventCountersAdded",
	game.EventDamageDealt:                 "game.EventDamageDealt",
	game.EventCardDrawn:                   "game.EventCardDrawn",
	game.EventZoneChanged:                 "game.EventZoneChanged",
	game.EventAttackerDeclared:            "game.EventAttackerDeclared",
	game.EventBlockerDeclared:             "game.EventBlockerDeclared",
	game.EventCardDiscarded:               "game.EventCardDiscarded",
	game.EventCycled:                      "game.EventCycled",
	game.EventDamagePrevented:             "game.EventDamagePrevented",
	game.EventDestroyReplaced:             "game.EventDestroyReplaced",
	game.EventBeginningOfStep:             "game.EventBeginningOfStep",
	game.EventLifeGained:                  "game.EventLifeGained",
	game.EventLifeLost:                    "game.EventLifeLost",
	game.EventPermanentTapped:             "game.EventPermanentTapped",
	game.EventPermanentUntapped:           "game.EventPermanentUntapped",
	game.EventObjectBecameTarget:          "game.EventObjectBecameTarget",
	game.EventCardRevealed:                "game.EventCardRevealed",
	game.EventPermanentTurnedFaceUp:       "game.EventPermanentTurnedFaceUp",
	game.EventPermanentSacrificed:         "game.EventPermanentSacrificed",
	game.EventScry:                        "game.EventScry",
	game.EventSurveil:                     "game.EventSurveil",
	game.EventAbilityActivated:            "game.EventAbilityActivated",
	game.EventFight:                       "game.EventFight",
	game.EventPermanentMutated:            "game.EventPermanentMutated",
	game.EventAttackerBecameBlocked:       "game.EventAttackerBecameBlocked",
	game.EventTokenCreated:                "game.EventTokenCreated",
	game.EventSpellCopied:                 "game.EventSpellCopied",
	game.EventPermanentPhasedOut:          "game.EventPermanentPhasedOut",
	game.EventPermanentPhasedIn:           "game.EventPermanentPhasedIn",
	game.EventLibrarySearched:             "game.EventLibrarySearched",
	game.EventAttackerBecameUnblocked:     "game.EventAttackerBecameUnblocked",
	game.EventClassLevelGained:            "game.EventClassLevelGained",
	game.EventCrimeCommitted:              "game.EventCrimeCommitted",
	game.EventBecameMonarch:               "game.EventBecameMonarch",
	game.EventCardPlayedFromExile:         "game.EventCardPlayedFromExile",
	game.EventLandPlayed:                  "game.EventLandPlayed",
	game.EventGotCityBlessing:             "game.EventGotCityBlessing",
	game.EventManaProduced:                "game.EventManaProduced",
	game.EventVenturedIntoDungeon:         "game.EventVenturedIntoDungeon",
	game.EventCompletedDungeon:            "game.EventCompletedDungeon",
	game.EventTookInitiative:              "game.EventTookInitiative",
	game.EventPermanentBecameMonstrous:    "game.EventPermanentBecameMonstrous",
}

// gameFaceDownKindLiterals maps each exported game.FaceDownKind constant to the Go
// expression that names it in generated card source.
var gameFaceDownKindLiterals = map[game.FaceDownKind]string{
	game.FaceDownNone:     "game.FaceDownNone",
	game.FaceDownMorph:    "game.FaceDownMorph",
	game.FaceDownDisguise: "game.FaceDownDisguise",
	game.FaceDownManifest: "game.FaceDownManifest",
	game.FaceDownCloak:    "game.FaceDownCloak",
	game.FaceDownEffect:   "game.FaceDownEffect",
}

// gameFaceIndexLiterals maps each exported game.FaceIndex constant to the Go
// expression that names it in generated card source.
var gameFaceIndexLiterals = map[game.FaceIndex]string{
	game.FaceFront:     "game.FaceFront",
	game.FaceBack:      "game.FaceBack",
	game.FaceAlternate: "game.FaceAlternate",
}

// gameGroupReferenceDomainLiterals maps each exported game.GroupReferenceDomain constant to the Go
// expression that names it in generated card source.
var gameGroupReferenceDomainLiterals = map[game.GroupReferenceDomain]string{
	game.GroupDomainBattlefield:           "game.GroupDomainBattlefield",
	game.GroupDomainAttachedObject:        "game.GroupDomainAttachedObject",
	game.GroupDomainObjectControlled:      "game.GroupDomainObjectControlled",
	game.GroupDomainPlayerControlled:      "game.GroupDomainPlayerControlled",
	game.GroupDomainSameName:              "game.GroupDomainSameName",
	game.GroupDomainTriggeringAttackers:   "game.GroupDomainTriggeringAttackers",
	game.GroupDomainCapturedObjects:       "game.GroupDomainCapturedObjects",
	game.GroupDomainLinkedObjects:         "game.GroupDomainLinkedObjects",
	game.GroupDomainAttackedThisTurn:      "game.GroupDomainAttackedThisTurn",
	game.GroupDomainPlayerGroupControlled: "game.GroupDomainPlayerGroupControlled",
	game.GroupDomainSaddleContributors:    "game.GroupDomainSaddleContributors",
}

// gameIterativeLibraryStopLiterals maps each exported game.IterativeLibraryStop constant to the Go
// expression that names it in generated card source.
var gameIterativeLibraryStopLiterals = map[game.IterativeLibraryStop]string{
	game.IterativeLibraryStopChosenName:           "game.IterativeLibraryStopChosenName",
	game.IterativeLibraryStopDuplicateName:        "game.IterativeLibraryStopDuplicateName",
	game.IterativeLibraryStopDifferentNameNonland: "game.IterativeLibraryStopDifferentNameNonland",
}

// gameKeywordLiterals maps each exported game.Keyword constant to the Go
// expression that names it in generated card source.
var gameKeywordLiterals = map[game.Keyword]string{
	game.KeywordNone:       "game.KeywordNone",
	game.Devoid:            "game.Devoid",
	game.Changeling:        "game.Changeling",
	game.Deathtouch:        "game.Deathtouch",
	game.Defender:          "game.Defender",
	game.DoubleStrike:      "game.DoubleStrike",
	game.FirstStrike:       "game.FirstStrike",
	game.Flash:             "game.Flash",
	game.Flying:            "game.Flying",
	game.Haste:             "game.Haste",
	game.Hexproof:          "game.Hexproof",
	game.Indestructible:    "game.Indestructible",
	game.Lifelink:          "game.Lifelink",
	game.Menace:            "game.Menace",
	game.Protection:        "game.Protection",
	game.Reach:             "game.Reach",
	game.Shroud:            "game.Shroud",
	game.Trample:           "game.Trample",
	game.Vigilance:         "game.Vigilance",
	game.Ward:              "game.Ward",
	game.SplitSecond:       "game.SplitSecond",
	game.Equip:             "game.Equip",
	game.Enchant:           "game.Enchant",
	game.Cycling:           "game.Cycling",
	game.Flashback:         "game.Flashback",
	game.Kicker:            "game.Kicker",
	game.Madness:           "game.Madness",
	game.Morph:             "game.Morph",
	game.Disguise:          "game.Disguise",
	game.Convoke:           "game.Convoke",
	game.Delve:             "game.Delve",
	game.Suspend:           "game.Suspend",
	game.Storm:             "game.Storm",
	game.Cascade:           "game.Cascade",
	game.Prowess:           "game.Prowess",
	game.Mutate:            "game.Mutate",
	game.Companion:         "game.Companion",
	game.Ninjutsu:          "game.Ninjutsu",
	game.Escape:            "game.Escape",
	game.Foretell:          "game.Foretell",
	game.Craft:             "game.Craft",
	game.Discover:          "game.Discover",
	game.Eternalize:        "game.Eternalize",
	game.Affinity:          "game.Affinity",
	game.Improvise:         "game.Improvise",
	game.Emerge:            "game.Emerge",
	game.Undying:           "game.Undying",
	game.Persist:           "game.Persist",
	game.Wither:            "game.Wither",
	game.Infect:            "game.Infect",
	game.Toxic:             "game.Toxic",
	game.Annihilator:       "game.Annihilator",
	game.Exalted:           "game.Exalted",
	game.ReadAhead:         "game.ReadAhead",
	game.Horsemanship:      "game.Horsemanship",
	game.CumulativeUpkeep:  "game.CumulativeUpkeep",
	game.Riot:              "game.Riot",
	game.Embalm:            "game.Embalm",
	game.Fear:              "game.Fear",
	game.Shadow:            "game.Shadow",
	game.Intimidate:        "game.Intimidate",
	game.Skulk:             "game.Skulk",
	game.Evolve:            "game.Evolve",
	game.Unleash:           "game.Unleash",
	game.Fabricate:         "game.Fabricate",
	game.Flanking:          "game.Flanking",
	game.Outlast:           "game.Outlast",
	game.Scavenge:          "game.Scavenge",
	game.Dethrone:          "game.Dethrone",
	game.Rampage:           "game.Rampage",
	game.LivingWeapon:      "game.LivingWeapon",
	game.Soulshift:         "game.Soulshift",
	game.Landwalk:          "game.Landwalk",
	game.Dredge:            "game.Dredge",
	game.Unearth:           "game.Unearth",
	game.Training:          "game.Training",
	game.Saddle:            "game.Saddle",
	game.Rebound:           "game.Rebound",
	game.Retrace:           "game.Retrace",
	game.Banding:           "game.Banding",
	game.Crew:              "game.Crew",
	game.Fuse:              "game.Fuse",
	game.JumpStart:         "game.JumpStart",
	game.PartnerWith:       "game.PartnerWith",
	game.ChooseABackground: "game.ChooseABackground",
	game.Reconfigure:       "game.Reconfigure",
	game.Partner:           "game.Partner",
	game.Hideaway:          "game.Hideaway",
	game.Plot:              "game.Plot",
	game.LivingMetal:       "game.LivingMetal",
	game.Gift:              "game.Gift",
	game.Myriad:            "game.Myriad",
	game.Mobilize:          "game.Mobilize",
	game.Transmute:         "game.Transmute",
	game.Echo:              "game.Echo",
	game.Splice:            "game.Splice",
	game.Bargain:           "game.Bargain",
	game.Bestow:            "game.Bestow",
	game.Offspring:         "game.Offspring",
	game.HexproofFrom:      "game.HexproofFrom",
	game.Ravenous:          "game.Ravenous",
	game.UmbraArmor:        "game.UmbraArmor",
	game.KeywordCount:      "game.KeywordCount",
}

// gameManaSpendConditionKindLiterals maps each exported game.ManaSpendConditionKind constant to the Go
// expression that names it in generated card source.
var gameManaSpendConditionKindLiterals = map[game.ManaSpendConditionKind]string{
	game.ManaSpendConditionUnknown:                  "game.ManaSpendConditionUnknown",
	game.ManaSpendCastCommanderCreatureType:         "game.ManaSpendCastCommanderCreatureType",
	game.ManaSpendCastChosenCreatureType:            "game.ManaSpendCastChosenCreatureType",
	game.ManaSpendCastLegendarySpell:                "game.ManaSpendCastLegendarySpell",
	game.ManaSpendCastOrActivateChosenCreatureType:  "game.ManaSpendCastOrActivateChosenCreatureType",
	game.ManaSpendCastCreatureSpell:                 "game.ManaSpendCastCreatureSpell",
	game.ManaSpendCastArtifactSpell:                 "game.ManaSpendCastArtifactSpell",
	game.ManaSpendCastArtifactSpellOnly:             "game.ManaSpendCastArtifactSpellOnly",
	game.ManaSpendCastOrActivateArtifact:            "game.ManaSpendCastOrActivateArtifact",
	game.ManaSpendActivateArtifactAbility:           "game.ManaSpendActivateArtifactAbility",
	game.ManaSpendCastArtifactOrActivateAbility:     "game.ManaSpendCastArtifactOrActivateAbility",
	game.ManaSpendCastInstantOrSorcerySpell:         "game.ManaSpendCastInstantOrSorcerySpell",
	game.ManaSpendCastNoncreatureSpell:              "game.ManaSpendCastNoncreatureSpell",
	game.ManaSpendCastMulticoloredSpell:             "game.ManaSpendCastMulticoloredSpell",
	game.ManaSpendCastPlaneswalkerSpell:             "game.ManaSpendCastPlaneswalkerSpell",
	game.ManaSpendCastOrActivateCreature:            "game.ManaSpendCastOrActivateCreature",
	game.ManaSpendCastMonocoloredSpellOfChosenColor: "game.ManaSpendCastMonocoloredSpellOfChosenColor",
}

// gameManaSpendRestrictionKindLiterals maps each exported game.ManaSpendRestrictionKind constant to the Go
// expression that names it in generated card source.
var gameManaSpendRestrictionKindLiterals = map[game.ManaSpendRestrictionKind]string{
	game.ManaSpendUnrestricted:          "game.ManaSpendUnrestricted",
	game.ManaSpendRestrictedToCondition: "game.ManaSpendRestrictedToCondition",
}

// gameMobilizeDynamicKindLiterals maps each exported game.MobilizeDynamicKind constant to the Go
// expression that names it in generated card source.
var gameMobilizeDynamicKindLiterals = map[game.MobilizeDynamicKind]string{
	game.MobilizeDynamicNone:                     "game.MobilizeDynamicNone",
	game.MobilizeDynamicCreatureCardsInGraveyard: "game.MobilizeDynamicCreatureCardsInGraveyard",
}

// gameModeChoiceConditionLiterals maps each exported game.ModeChoiceCondition constant to the Go
// expression that names it in generated card source.
var gameModeChoiceConditionLiterals = map[game.ModeChoiceCondition]string{
	game.ModeChoiceConditionNone:              "game.ModeChoiceConditionNone",
	game.ModeChoiceConditionControlsCommander: "game.ModeChoiceConditionControlsCommander",
	game.ModeChoiceConditionSpellKicked:       "game.ModeChoiceConditionSpellKicked",
}

// gameObjectReferenceKindLiterals maps each exported game.ObjectReferenceKind constant to the Go
// expression that names it in generated card source.
var gameObjectReferenceKindLiterals = map[game.ObjectReferenceKind]string{
	game.ObjectReferenceNone:                      "game.ObjectReferenceNone",
	game.ObjectReferenceTargetPermanent:           "game.ObjectReferenceTargetPermanent",
	game.ObjectReferenceTargetStackObject:         "game.ObjectReferenceTargetStackObject",
	game.ObjectReferenceSourcePermanent:           "game.ObjectReferenceSourcePermanent",
	game.ObjectReferenceSourceAttachedPermanent:   "game.ObjectReferenceSourceAttachedPermanent",
	game.ObjectReferenceTargetAttachedPermanent:   "game.ObjectReferenceTargetAttachedPermanent",
	game.ObjectReferenceLinkedObject:              "game.ObjectReferenceLinkedObject",
	game.ObjectReferenceEventPermanent:            "game.ObjectReferenceEventPermanent",
	game.ObjectReferenceSourceCard:                "game.ObjectReferenceSourceCard",
	game.ObjectReferenceCapturedTargetStackObject: "game.ObjectReferenceCapturedTargetStackObject",
	game.ObjectReferenceTargetObject:              "game.ObjectReferenceTargetObject",
	game.ObjectReferenceSacrificedCost:            "game.ObjectReferenceSacrificedCost",
	game.ObjectReferenceEventRelatedPermanent:     "game.ObjectReferenceEventRelatedPermanent",
	game.ObjectReferenceEventStackObject:          "game.ObjectReferenceEventStackObject",
	game.ObjectReferenceResolvingStackObject:      "game.ObjectReferenceResolvingStackObject",
	game.ObjectReferenceAllTargetPermanents:       "game.ObjectReferenceAllTargetPermanents",
	game.ObjectReferenceCapturedObject:            "game.ObjectReferenceCapturedObject",
	game.ObjectReferenceTargetCard:                "game.ObjectReferenceTargetCard",
	game.ObjectReferenceAllTargetStackObjects:     "game.ObjectReferenceAllTargetStackObjects",
}

// gameOwnerRelationLiterals maps each exported game.OwnerRelation constant to the Go
// expression that names it in generated card source.
var gameOwnerRelationLiterals = map[game.OwnerRelation]string{
	game.OwnerAny:      "game.OwnerAny",
	game.OwnerYou:      "game.OwnerYou",
	game.OwnerOpponent: "game.OwnerOpponent",
	game.OwnerNotYou:   "game.OwnerNotYou",
}

// gamePermanentChoiceExtremumLiterals maps each exported game.PermanentChoiceExtremum constant to the Go
// expression that names it in generated card source.
var gamePermanentChoiceExtremumLiterals = map[game.PermanentChoiceExtremum]string{
	game.PermanentChoiceExtremumNone:      "game.PermanentChoiceExtremumNone",
	game.PermanentChoiceGreatestPower:     "game.PermanentChoiceGreatestPower",
	game.PermanentChoiceGreatestToughness: "game.PermanentChoiceGreatestToughness",
	game.PermanentChoiceGreatestManaValue: "game.PermanentChoiceGreatestManaValue",
}

// gamePlayerGroupReferenceKindLiterals maps each exported game.PlayerGroupReferenceKind constant to the Go
// expression that names it in generated card source.
var gamePlayerGroupReferenceKindLiterals = map[game.PlayerGroupReferenceKind]string{
	game.PlayerGroupReferenceNone:                                      "game.PlayerGroupReferenceNone",
	game.PlayerGroupReferenceOpponents:                                 "game.PlayerGroupReferenceOpponents",
	game.PlayerGroupReferenceAllPlayers:                                "game.PlayerGroupReferenceAllPlayers",
	game.PlayerGroupReferenceTargetedPlayers:                           "game.PlayerGroupReferenceTargetedPlayers",
	game.PlayerGroupReferenceOpponentsAttackingTriggerPlayer:           "game.PlayerGroupReferenceOpponentsAttackingTriggerPlayer",
	game.PlayerGroupReferenceOpponentsDealtCombatDamageThisGameByNamed: "game.PlayerGroupReferenceOpponentsDealtCombatDamageThisGameByNamed",
}

// gamePlayerIDLiterals maps each exported game.PlayerID constant to the Go
// expression that names it in generated card source.
var gamePlayerIDLiterals = map[game.PlayerID]string{
	game.Player1: "game.Player1",
	game.Player2: "game.Player2",
	game.Player3: "game.Player3",
	game.Player4: "game.Player4",
}

// gamePlayerReferenceKindLiterals maps each exported game.PlayerReferenceKind constant to the Go
// expression that names it in generated card source.
var gamePlayerReferenceKindLiterals = map[game.PlayerReferenceKind]string{
	game.PlayerReferenceNone:                     "game.PlayerReferenceNone",
	game.PlayerReferenceController:               "game.PlayerReferenceController",
	game.PlayerReferenceTargetPlayer:             "game.PlayerReferenceTargetPlayer",
	game.PlayerReferenceObjectController:         "game.PlayerReferenceObjectController",
	game.PlayerReferenceObjectOwner:              "game.PlayerReferenceObjectOwner",
	game.PlayerReferenceEventPlayer:              "game.PlayerReferenceEventPlayer",
	game.PlayerReferenceCapturedTargetController: "game.PlayerReferenceCapturedTargetController",
	game.PlayerReferenceDefendingPlayer:          "game.PlayerReferenceDefendingPlayer",
	game.PlayerReferenceGroupOfferMember:         "game.PlayerReferenceGroupOfferMember",
	game.PlayerReferenceAffectedTargetController: "game.PlayerReferenceAffectedTargetController",
	game.PlayerReferenceGiftRecipient:            "game.PlayerReferenceGiftRecipient",
}

// gamePlayerRelationLiterals maps each exported game.PlayerRelation constant to the Go
// expression that names it in generated card source.
var gamePlayerRelationLiterals = map[game.PlayerRelation]string{
	game.PlayerAny:      "game.PlayerAny",
	game.PlayerYou:      "game.PlayerYou",
	game.PlayerOpponent: "game.PlayerOpponent",
	game.PlayerNotYou:   "game.PlayerNotYou",
}

// gameResolutionChoiceColorSourceLiterals maps each exported game.ResolutionChoiceColorSource constant to the Go
// expression that names it in generated card source.
var gameResolutionChoiceColorSourceLiterals = map[game.ResolutionChoiceColorSource]string{
	game.ResolutionChoiceColorSourceStatic:                    "game.ResolutionChoiceColorSourceStatic",
	game.ResolutionChoiceColorSourceCommanderIdentity:         "game.ResolutionChoiceColorSourceCommanderIdentity",
	game.ResolutionChoiceColorSourceFixedOrEntryChosen:        "game.ResolutionChoiceColorSourceFixedOrEntryChosen",
	game.ResolutionChoiceColorSourceLandsProduce:              "game.ResolutionChoiceColorSourceLandsProduce",
	game.ResolutionChoiceColorSourceLinkedExileColors:         "game.ResolutionChoiceColorSourceLinkedExileColors",
	game.ResolutionChoiceColorSourceControlledPermanentColors: "game.ResolutionChoiceColorSourceControlledPermanentColors",
	game.ResolutionChoiceColorSourceTriggerLandProduced:       "game.ResolutionChoiceColorSourceTriggerLandProduced",
}

// gameResolutionChoiceKindLiterals maps each exported game.ResolutionChoiceKind constant to the Go
// expression that names it in generated card source.
var gameResolutionChoiceKindLiterals = map[game.ResolutionChoiceKind]string{
	game.ResolutionChoiceNone:      "game.ResolutionChoiceNone",
	game.ResolutionChoiceMana:      "game.ResolutionChoiceMana",
	game.ResolutionChoiceCardType:  "game.ResolutionChoiceCardType",
	game.ResolutionChoicePlayer:    "game.ResolutionChoicePlayer",
	game.ResolutionChoiceCard:      "game.ResolutionChoiceCard",
	game.ResolutionChoiceSubtype:   "game.ResolutionChoiceSubtype",
	game.ResolutionChoiceNumber:    "game.ResolutionChoiceNumber",
	game.ResolutionChoiceCardName:  "game.ResolutionChoiceCardName",
	game.ResolutionChoicePermanent: "game.ResolutionChoicePermanent",
}

// gameRuleEffectKindLiterals maps each exported game.RuleEffectKind constant to the Go
// expression that names it in generated card source.
var gameRuleEffectKindLiterals = map[game.RuleEffectKind]string{
	game.RuleEffectNone:                                    "game.RuleEffectNone",
	game.RuleEffectCantGainLife:                            "game.RuleEffectCantGainLife",
	game.RuleEffectCantAttack:                              "game.RuleEffectCantAttack",
	game.RuleEffectCantBlock:                               "game.RuleEffectCantBlock",
	game.RuleEffectCostModifier:                            "game.RuleEffectCostModifier",
	game.RuleEffectCastFromZone:                            "game.RuleEffectCastFromZone",
	game.RuleEffectCantBeCountered:                         "game.RuleEffectCantBeCountered",
	game.RuleEffectCantBeBlocked:                           "game.RuleEffectCantBeBlocked",
	game.RuleEffectMustBeBlocked:                           "game.RuleEffectMustBeBlocked",
	game.RuleEffectMustAttack:                              "game.RuleEffectMustAttack",
	game.RuleEffectGrantHandCardAbility:                    "game.RuleEffectGrantHandCardAbility",
	game.RuleEffectGrantGraveyardCardKeyword:               "game.RuleEffectGrantGraveyardCardKeyword",
	game.RuleEffectDoesntUntap:                             "game.RuleEffectDoesntUntap",
	game.RuleEffectCantBeBlockedByMoreThanOne:              "game.RuleEffectCantBeBlockedByMoreThanOne",
	game.RuleEffectNoMaximumHandSize:                       "game.RuleEffectNoMaximumHandSize",
	game.RuleEffectCantBeBlockedByCreaturesWith:            "game.RuleEffectCantBeBlockedByCreaturesWith",
	game.RuleEffectCantBeBlockedExceptBy:                   "game.RuleEffectCantBeBlockedExceptBy",
	game.RuleEffectCombatDamageCantBePrevented:             "game.RuleEffectCombatDamageCantBePrevented",
	game.RuleEffectPlayerProtection:                        "game.RuleEffectPlayerProtection",
	game.RuleEffectAttackTax:                               "game.RuleEffectAttackTax",
	game.RuleEffectLifeTotalCantChange:                     "game.RuleEffectLifeTotalCantChange",
	game.RuleEffectPlayFromZone:                            "game.RuleEffectPlayFromZone",
	game.RuleEffectAdditionalTriggerForChosenCreatureType:  "game.RuleEffectAdditionalTriggerForChosenCreatureType",
	game.RuleEffectAdditionalLandPlays:                     "game.RuleEffectAdditionalLandPlays",
	game.RuleEffectCantCastSpells:                          "game.RuleEffectCantCastSpells",
	game.RuleEffectCantActivateAbilities:                   "game.RuleEffectCantActivateAbilities",
	game.RuleEffectAdditionalTriggerForEnteringPermanent:   "game.RuleEffectAdditionalTriggerForEnteringPermanent",
	game.RuleEffectUntapDuringOtherPlayersUntapStep:        "game.RuleEffectUntapDuringOtherPlayersUntapStep",
	game.RuleEffectCastSpellsAsThoughFlash:                 "game.RuleEffectCastSpellsAsThoughFlash",
	game.RuleEffectPlayLandsFromZone:                       "game.RuleEffectPlayLandsFromZone",
	game.RuleEffectPlayWithTopCardRevealed:                 "game.RuleEffectPlayWithTopCardRevealed",
	game.RuleEffectCastSpellsFromZone:                      "game.RuleEffectCastSpellsFromZone",
	game.RuleEffectCantCastFromZones:                       "game.RuleEffectCantCastFromZones",
	game.RuleEffectCantEnterFromZones:                      "game.RuleEffectCantEnterFromZones",
	game.RuleEffectLookAtTopCardAnyTime:                    "game.RuleEffectLookAtTopCardAnyTime",
	game.RuleEffectPayLifeForColoredMana:                   "game.RuleEffectPayLifeForColoredMana",
	game.RuleEffectPayLifeForCommanderTax:                  "game.RuleEffectPayLifeForCommanderTax",
	game.RuleEffectDrawLimitPerTurn:                        "game.RuleEffectDrawLimitPerTurn",
	game.RuleEffectCastLimitPerTurn:                        "game.RuleEffectCastLimitPerTurn",
	game.RuleEffectAdditionalTriggerForControlledPermanent: "game.RuleEffectAdditionalTriggerForControlledPermanent",
	game.RuleEffectMustBeBlockedByAllAble:                  "game.RuleEffectMustBeBlockedByAllAble",
	game.RuleEffectAssignCombatDamageAsThoughUnblocked:     "game.RuleEffectAssignCombatDamageAsThoughUnblocked",
	game.RuleEffectCantTransform:                           "game.RuleEffectCantTransform",
	game.RuleEffectSuppressOpponentEnteringTriggers:        "game.RuleEffectSuppressOpponentEnteringTriggers",
	game.RuleEffectAttackTaxPerCreature:                    "game.RuleEffectAttackTaxPerCreature",
	game.RuleEffectManaProductionMultiplier:                "game.RuleEffectManaProductionMultiplier",
	game.RuleEffectSkipDrawStep:                            "game.RuleEffectSkipDrawStep",
	game.RuleEffectCanBlockOnlyCreaturesWith:               "game.RuleEffectCanBlockOnlyCreaturesWith",
	game.RuleEffectCantAttackAlone:                         "game.RuleEffectCantAttackAlone",
	game.RuleEffectCantBlockAlone:                          "game.RuleEffectCantBlockAlone",
	game.RuleEffectCanAttackAsThoughDefender:               "game.RuleEffectCanAttackAsThoughDefender",
	game.RuleEffectAssignCombatDamageUsingToughness:        "game.RuleEffectAssignCombatDamageUsingToughness",
	game.RuleEffectCantActivateAbilitiesOfPermanent:        "game.RuleEffectCantActivateAbilitiesOfPermanent",
	game.RuleEffectGoaded:                                  "game.RuleEffectGoaded",
	game.RuleEffectPlayerHexproof:                          "game.RuleEffectPlayerHexproof",
	game.RuleEffectPlayerShroud:                            "game.RuleEffectPlayerShroud",
	game.RuleEffectCanBlockAdditional:                      "game.RuleEffectCanBlockAdditional",
	game.RuleEffectDamageDoesntCauseLifeLoss:               "game.RuleEffectDamageDoesntCauseLifeLoss",
	game.RuleEffectRedirectDamageToSource:                  "game.RuleEffectRedirectDamageToSource",
	game.RuleEffectCantBeSacrificed:                        "game.RuleEffectCantBeSacrificed",
	game.RuleEffectCastLinkedExileForFree:                  "game.RuleEffectCastLinkedExileForFree",
	game.RuleEffectActivateAbilitiesAsThoughHaste:          "game.RuleEffectActivateAbilitiesAsThoughHaste",
	game.RuleEffectGrantSpellKeyword:                       "game.RuleEffectGrantSpellKeyword",
	game.RuleEffectAscend:                                  "game.RuleEffectAscend",
	game.RuleEffectCantBeTargetedByControllerOpponents:     "game.RuleEffectCantBeTargetedByControllerOpponents",
	game.RuleEffectSkipExtraTurns:                          "game.RuleEffectSkipExtraTurns",
	game.RuleEffectAdditionalTriggerForRoomAbility:         "game.RuleEffectAdditionalTriggerForRoomAbility",
	game.RuleEffectControlOpponentSearches:                 "game.RuleEffectControlOpponentSearches",
	game.RuleEffectExileOpponentSearchFinds:                "game.RuleEffectExileOpponentSearchFinds",
	game.RuleEffectLegendRuleDoesNotApply:                  "game.RuleEffectLegendRuleDoesNotApply",
}

// gameSacrificeFallbackKindLiterals maps each exported game.SacrificeFallbackKind constant to the Go
// expression that names it in generated card source.
var gameSacrificeFallbackKindLiterals = map[game.SacrificeFallbackKind]string{
	game.SacrificeFallbackNone:     "game.SacrificeFallbackNone",
	game.SacrificeFallbackDiscard:  "game.SacrificeFallbackDiscard",
	game.SacrificeFallbackLoseLife: "game.SacrificeFallbackLoseLife",
}

// gameSearchFailToFindPolicyLiterals maps each exported game.SearchFailToFindPolicy constant to the Go
// expression that names it in generated card source.
var gameSearchFailToFindPolicyLiterals = map[game.SearchFailToFindPolicy]string{
	game.SearchFailToFindDefault:   "game.SearchFailToFindDefault",
	game.SearchMayFailToFind:       "game.SearchMayFailToFind",
	game.SearchMustFindIfAvailable: "game.SearchMustFindIfAvailable",
}

// gameSearchPositionLiterals maps each exported game.SearchPosition constant to the Go
// expression that names it in generated card source.
var gameSearchPositionLiterals = map[game.SearchPosition]string{
	game.SearchPositionUnspecified: "game.SearchPositionUnspecified",
	game.SearchPositionTop:         "game.SearchPositionTop",
}

// gameSourcePowerToughnessLiterals maps each exported game.SourcePowerToughness constant to the Go
// expression that names it in generated card source.
var gameSourcePowerToughnessLiterals = map[game.SourcePowerToughness]string{
	game.SourcePowerToughnessNone: "game.SourcePowerToughnessNone",
	game.SourcePower:              "game.SourcePower",
	game.SourceToughness:          "game.SourceToughness",
}

// gameSpellTargetRequirementKindLiterals maps each exported game.SpellTargetRequirementKind constant to the Go
// expression that names it in generated card source.
var gameSpellTargetRequirementKindLiterals = map[game.SpellTargetRequirementKind]string{
	game.SpellTargetRequirementPermanent: "game.SpellTargetRequirementPermanent",
	game.SpellTargetRequirementPlayer:    "game.SpellTargetRequirementPlayer",
}

// gameStackObjectKindLiterals maps each exported game.StackObjectKind constant to the Go
// expression that names it in generated card source.
var gameStackObjectKindLiterals = map[game.StackObjectKind]string{
	game.StackSpell:            "game.StackSpell",
	game.StackActivatedAbility: "game.StackActivatedAbility",
	game.StackTriggeredAbility: "game.StackTriggeredAbility",
}

// gameStepLiterals maps each exported game.Step constant to the Go
// expression that names it in generated card source.
var gameStepLiterals = map[game.Step]string{
	game.StepNone:              "game.StepNone",
	game.StepUntap:             "game.StepUntap",
	game.StepUpkeep:            "game.StepUpkeep",
	game.StepDraw:              "game.StepDraw",
	game.StepBeginningOfCombat: "game.StepBeginningOfCombat",
	game.StepDeclareAttackers:  "game.StepDeclareAttackers",
	game.StepDeclareBlockers:   "game.StepDeclareBlockers",
	game.StepFirstStrikeDamage: "game.StepFirstStrikeDamage",
	game.StepCombatDamage:      "game.StepCombatDamage",
	game.StepEndOfCombat:       "game.StepEndOfCombat",
	game.StepEnd:               "game.StepEnd",
	game.StepCleanup:           "game.StepCleanup",
	game.StepPrecombatMain:     "game.StepPrecombatMain",
	game.StepPostcombatMain:    "game.StepPostcombatMain",
}

// gameSubtypeChoiceSourceLiterals maps each exported game.SubtypeChoiceSource constant to the Go
// expression that names it in generated card source.
var gameSubtypeChoiceSourceLiterals = map[game.SubtypeChoiceSource]string{
	game.SubtypeChoiceNone:               "game.SubtypeChoiceNone",
	game.SubtypeChoiceSourceEntry:        "game.SubtypeChoiceSourceEntry",
	game.SubtypeChoiceResolution:         "game.SubtypeChoiceResolution",
	game.SubtypeChoiceResolutionExcluded: "game.SubtypeChoiceResolutionExcluded",
}

// gameTargetAllowFlags lists every exported game.TargetAllow flag in ascending
// value order, which is the order set flags are ORed together in generated
// card source.
var gameTargetAllowFlags = []enumFlag[game.TargetAllow]{
	{Flag: game.TargetAllowPermanent, Literal: "game.TargetAllowPermanent"},
	{Flag: game.TargetAllowPlayer, Literal: "game.TargetAllowPlayer"},
	{Flag: game.TargetAllowStackObject, Literal: "game.TargetAllowStackObject"},
	{Flag: game.TargetAllowCard, Literal: "game.TargetAllowCard"},
}

// gameTargetChooserLiterals maps each exported game.TargetChooser constant to the Go
// expression that names it in generated card source.
var gameTargetChooserLiterals = map[game.TargetChooser]string{
	game.TargetChooserController: "game.TargetChooserController",
	game.TargetChooserOpponent:   "game.TargetChooserOpponent",
}

// gameTargetGateLiterals maps each exported game.TargetGate constant to the Go
// expression that names it in generated card source.
var gameTargetGateLiterals = map[game.TargetGate]string{
	game.TargetGateAlways:            "game.TargetGateAlways",
	game.TargetGateGiftPromised:      "game.TargetGateGiftPromised",
	game.TargetGateGiftNotPromised:   "game.TargetGateGiftNotPromised",
	game.TargetGateSpellKicked:       "game.TargetGateSpellKicked",
	game.TargetGateSpellNotKicked:    "game.TargetGateSpellNotKicked",
	game.TargetGateSpellBargained:    "game.TargetGateSpellBargained",
	game.TargetGateSpellNotBargained: "game.TargetGateSpellNotBargained",
	game.TargetGateBestowed:          "game.TargetGateBestowed",
	game.TargetGateSpellOffspring:    "game.TargetGateSpellOffspring",
	game.TargetGateSpellNotOffspring: "game.TargetGateSpellNotOffspring",
}

// gameTimingRestrictionLiterals maps each exported game.TimingRestriction constant to the Go
// expression that names it in generated card source.
var gameTimingRestrictionLiterals = map[game.TimingRestriction]string{
	game.NoTimingRestriction:           "game.NoTimingRestriction",
	game.SorceryOnly:                   "game.SorceryOnly",
	game.OncePerTurn:                   "game.OncePerTurn",
	game.SorceryOncePerTurn:            "game.SorceryOncePerTurn",
	game.DuringCombat:                  "game.DuringCombat",
	game.DuringUpkeep:                  "game.DuringUpkeep",
	game.DuringYourTurn:                "game.DuringYourTurn",
	game.DuringYourTurnBeforeAttackers: "game.DuringYourTurnBeforeAttackers",
}

// gameTokenCopySourceLiterals maps each exported game.TokenCopySource constant to the Go
// expression that names it in generated card source.
var gameTokenCopySourceLiterals = map[game.TokenCopySource]string{
	game.TokenCopySourceNone:                          "game.TokenCopySourceNone",
	game.TokenCopySourceObject:                        "game.TokenCopySourceObject",
	game.TokenCopySourceSourceCard:                    "game.TokenCopySourceSourceCard",
	game.TokenCopySourceEachInGroup:                   "game.TokenCopySourceEachInGroup",
	game.TokenCopySourceChosenFromTriggerBatch:        "game.TokenCopySourceChosenFromTriggerBatch",
	game.TokenCopySourceChosenControlledCreatureToken: "game.TokenCopySourceChosenControlledCreatureToken",
	game.TokenCopySourceChosenFromGroup:               "game.TokenCopySourceChosenFromGroup",
	game.TokenCopySourceLinkedExiledCard:              "game.TokenCopySourceLinkedExiledCard",
}

// gameTriStateLiterals maps each exported game.TriState constant to the Go
// expression that names it in generated card source.
var gameTriStateLiterals = map[game.TriState]string{
	game.TriAny:   "game.TriAny",
	game.TriTrue:  "game.TriTrue",
	game.TriFalse: "game.TriFalse",
}

// gameTriggerControllerFilterLiterals maps each exported game.TriggerControllerFilter constant to the Go
// expression that names it in generated card source.
var gameTriggerControllerFilterLiterals = map[game.TriggerControllerFilter]string{
	game.TriggerControllerAny:      "game.TriggerControllerAny",
	game.TriggerControllerYou:      "game.TriggerControllerYou",
	game.TriggerControllerOpponent: "game.TriggerControllerOpponent",
}

// gameTriggerPlayerFilterLiterals maps each exported game.TriggerPlayerFilter constant to the Go
// expression that names it in generated card source.
var gameTriggerPlayerFilterLiterals = map[game.TriggerPlayerFilter]string{
	game.TriggerPlayerAny:        "game.TriggerPlayerAny",
	game.TriggerPlayerYou:        "game.TriggerPlayerYou",
	game.TriggerPlayerOpponent:   "game.TriggerPlayerOpponent",
	game.TriggerPlayerMonarch:    "game.TriggerPlayerMonarch",
	game.TriggerPlayerInitiative: "game.TriggerPlayerInitiative",
}

// gameTriggerSourceFilterLiterals maps each exported game.TriggerSourceFilter constant to the Go
// expression that names it in generated card source.
var gameTriggerSourceFilterLiterals = map[game.TriggerSourceFilter]string{
	game.TriggerSourceAny:               "game.TriggerSourceAny",
	game.TriggerSourceSelf:              "game.TriggerSourceSelf",
	game.TriggerSourceAttachedPermanent: "game.TriggerSourceAttachedPermanent",
}

// gameTriggerSubjectObjectLiterals maps each exported game.TriggerSubjectObject constant to the Go
// expression that names it in generated card source.
var gameTriggerSubjectObjectLiterals = map[game.TriggerSubjectObject]string{
	game.TriggerSubjectDefault:         "game.TriggerSubjectDefault",
	game.TriggerSubjectPermanent:       "game.TriggerSubjectPermanent",
	game.TriggerSubjectBlockedAttacker: "game.TriggerSubjectBlockedAttacker",
	game.TriggerSubjectDamageSource:    "game.TriggerSubjectDamageSource",
}

// gameTriggerTurnRelationLiterals maps each exported game.TriggerTurnRelation constant to the Go
// expression that names it in generated card source.
var gameTriggerTurnRelationLiterals = map[game.TriggerTurnRelation]string{
	game.TriggerTurnAny:         "game.TriggerTurnAny",
	game.TriggerTurnYours:       "game.TriggerTurnYours",
	game.TriggerTurnNotYours:    "game.TriggerTurnNotYours",
	game.TriggerTurnEventPlayer: "game.TriggerTurnEventPlayer",
}

// gameTriggerTypeLiterals maps each exported game.TriggerType constant to the Go
// expression that names it in generated card source.
var gameTriggerTypeLiterals = map[game.TriggerType]string{
	game.TriggerWhen:     "game.TriggerWhen",
	game.TriggerWhenever: "game.TriggerWhenever",
	game.TriggerAt:       "game.TriggerAt",
	game.TriggerState:    "game.TriggerState",
}

// manaColorLiterals maps each exported mana.Color constant to the Go
// expression that names it in generated card source.
var manaColorLiterals = map[mana.Color]string{
	mana.W: "mana.W",
	mana.U: "mana.U",
	mana.B: "mana.B",
	mana.R: "mana.R",
	mana.G: "mana.G",
	mana.C: "mana.C",
}

// typesCardLiterals maps each exported types.Card constant to the Go
// expression that names it in generated card source.
var typesCardLiterals = map[types.Card]string{
	types.Land:         "types.Land",
	types.Creature:     "types.Creature",
	types.Artifact:     "types.Artifact",
	types.Enchantment:  "types.Enchantment",
	types.Instant:      "types.Instant",
	types.Sorcery:      "types.Sorcery",
	types.Planeswalker: "types.Planeswalker",
	types.Battle:       "types.Battle",
	types.Kindred:      "types.Kindred",
	types.Plane:        "types.Plane",
	types.Dungeon:      "types.Dungeon",
	types.Phenomenon:   "types.Phenomenon",
	types.Scheme:       "types.Scheme",
	types.Vanguard:     "types.Vanguard",
	types.Conspiracy:   "types.Conspiracy",
}

// typesSubLiterals maps each exported types.Sub constant to the Go
// expression that names it in generated card source.
var typesSubLiterals = map[types.Sub]string{
	types.Attraction:            "types.Attraction",
	types.Blood:                 "types.Blood",
	types.Bobblehead:            "types.Bobblehead",
	types.Book:                  "types.Book",
	types.Clue:                  "types.Clue",
	types.Contraption:           "types.Contraption",
	types.Equipment:             "types.Equipment",
	types.Food:                  "types.Food",
	types.Fortification:         "types.Fortification",
	types.Gold:                  "types.Gold",
	types.Incubator:             "types.Incubator",
	types.Infinity:              "types.Infinity",
	types.Junk:                  "types.Junk",
	types.Lander:                "types.Lander",
	types.Map:                   "types.Map",
	types.Mutagen:               "types.Mutagen",
	types.Powerstone:            "types.Powerstone",
	types.ArtifactSpacecraft:    "types.ArtifactSpacecraft", // also PlanarSpacecraft
	types.Stone:                 "types.Stone",
	types.Treasure:              "types.Treasure",
	types.Vehicle:               "types.Vehicle",
	types.Siege:                 "types.Siege",
	types.TimeLord:              "types.TimeLord",
	types.Advisor:               "types.Advisor",
	types.Aetherborn:            "types.Aetherborn",
	types.Alien:                 "types.Alien",
	types.Ally:                  "types.Ally",
	types.Angel:                 "types.Angel",
	types.Antelope:              "types.Antelope",
	types.Ape:                   "types.Ape",
	types.Archer:                "types.Archer",
	types.Archon:                "types.Archon",
	types.Armadillo:             "types.Armadillo",
	types.Army:                  "types.Army",
	types.Artificer:             "types.Artificer",
	types.Assassin:              "types.Assassin",
	types.AssemblyWorker:        "types.AssemblyWorker",
	types.Astartes:              "types.Astartes",
	types.Atog:                  "types.Atog",
	types.Aurochs:               "types.Aurochs",
	types.Avatar:                "types.Avatar",
	types.Azra:                  "types.Azra",
	types.Badger:                "types.Badger",
	types.Balloon:               "types.Balloon",
	types.Barbarian:             "types.Barbarian",
	types.Bard:                  "types.Bard",
	types.Basilisk:              "types.Basilisk",
	types.Bat:                   "types.Bat",
	types.Bear:                  "types.Bear",
	types.Beast:                 "types.Beast",
	types.Beaver:                "types.Beaver",
	types.Beeble:                "types.Beeble",
	types.Beholder:              "types.Beholder",
	types.Berserker:             "types.Berserker",
	types.Bird:                  "types.Bird",
	types.Bison:                 "types.Bison",
	types.Blinkmoth:             "types.Blinkmoth",
	types.Boar:                  "types.Boar",
	types.Bringer:               "types.Bringer",
	types.Brushwagg:             "types.Brushwagg",
	types.Camarid:               "types.Camarid",
	types.Camel:                 "types.Camel",
	types.Capybara:              "types.Capybara",
	types.Caribou:               "types.Caribou",
	types.Carrier:               "types.Carrier",
	types.Cat:                   "types.Cat",
	types.Centaur:               "types.Centaur",
	types.Child:                 "types.Child",
	types.Chimera:               "types.Chimera",
	types.Citizen:               "types.Citizen",
	types.Cleric:                "types.Cleric",
	types.Clown:                 "types.Clown",
	types.Cockatrice:            "types.Cockatrice",
	types.Construct:             "types.Construct",
	types.Coward:                "types.Coward",
	types.Coyote:                "types.Coyote",
	types.Crab:                  "types.Crab",
	types.Crocodile:             "types.Crocodile",
	types.Ctan:                  "types.Ctan",
	types.Custodes:              "types.Custodes",
	types.Cyberman:              "types.Cyberman",
	types.Cyclops:               "types.Cyclops",
	types.Dalek:                 "types.Dalek",
	types.Dauthi:                "types.Dauthi",
	types.Demigod:               "types.Demigod",
	types.Demon:                 "types.Demon",
	types.Deserter:              "types.Deserter",
	types.Detective:             "types.Detective",
	types.Devil:                 "types.Devil",
	types.Dinosaur:              "types.Dinosaur",
	types.Djinn:                 "types.Djinn",
	types.Doctor:                "types.Doctor",
	types.Dog:                   "types.Dog",
	types.Dragon:                "types.Dragon",
	types.Drake:                 "types.Drake",
	types.Dreadnought:           "types.Dreadnought",
	types.Drix:                  "types.Drix",
	types.Drone:                 "types.Drone",
	types.Druid:                 "types.Druid",
	types.Dryad:                 "types.Dryad",
	types.Dwarf:                 "types.Dwarf",
	types.Echidna:               "types.Echidna",
	types.Efreet:                "types.Efreet",
	types.Egg:                   "types.Egg",
	types.Elder:                 "types.Elder",
	types.Eldrazi:               "types.Eldrazi",
	types.Elemental:             "types.Elemental",
	types.Elephant:              "types.Elephant",
	types.Elf:                   "types.Elf",
	types.Elk:                   "types.Elk",
	types.Employee:              "types.Employee",
	types.Eye:                   "types.Eye",
	types.Faerie:                "types.Faerie",
	types.Ferret:                "types.Ferret",
	types.Fish:                  "types.Fish",
	types.Flagbearer:            "types.Flagbearer",
	types.Fox:                   "types.Fox",
	types.Fractal:               "types.Fractal",
	types.Frog:                  "types.Frog",
	types.Fungus:                "types.Fungus",
	types.Gamer:                 "types.Gamer",
	types.Gargoyle:              "types.Gargoyle",
	types.Germ:                  "types.Germ",
	types.Giant:                 "types.Giant",
	types.Giraffe:               "types.Giraffe",
	types.Gith:                  "types.Gith",
	types.Glimmer:               "types.Glimmer",
	types.Gnoll:                 "types.Gnoll",
	types.Gnome:                 "types.Gnome",
	types.Goat:                  "types.Goat",
	types.Goblin:                "types.Goblin",
	types.God:                   "types.God",
	types.Golem:                 "types.Golem",
	types.Gorgon:                "types.Gorgon",
	types.Graveborn:             "types.Graveborn",
	types.Gremlin:               "types.Gremlin",
	types.Griffin:               "types.Griffin",
	types.Guest:                 "types.Guest",
	types.Hag:                   "types.Hag",
	types.Halfling:              "types.Halfling",
	types.Hamster:               "types.Hamster",
	types.Harpy:                 "types.Harpy",
	types.Hedgehog:              "types.Hedgehog",
	types.Hellion:               "types.Hellion",
	types.Hero:                  "types.Hero",
	types.Hippo:                 "types.Hippo",
	types.Hippogriff:            "types.Hippogriff",
	types.Homarid:               "types.Homarid",
	types.Homunculus:            "types.Homunculus",
	types.Horror:                "types.Horror",
	types.Horse:                 "types.Horse",
	types.Human:                 "types.Human",
	types.Hydra:                 "types.Hydra",
	types.Hyena:                 "types.Hyena",
	types.Illusion:              "types.Illusion",
	types.Imp:                   "types.Imp",
	types.Incarnation:           "types.Incarnation",
	types.Inkling:               "types.Inkling",
	types.Inquisitor:            "types.Inquisitor",
	types.Insect:                "types.Insect",
	types.Jackal:                "types.Jackal",
	types.Jellyfish:             "types.Jellyfish",
	types.Juggernaut:            "types.Juggernaut",
	types.Kangaroo:              "types.Kangaroo",
	types.Kavu:                  "types.Kavu",
	types.Kirin:                 "types.Kirin",
	types.Kithkin:               "types.Kithkin",
	types.Knight:                "types.Knight",
	types.Kobold:                "types.Kobold",
	types.Kor:                   "types.Kor",
	types.Kraken:                "types.Kraken",
	types.Llama:                 "types.Llama",
	types.Lamia:                 "types.Lamia",
	types.Lammasu:               "types.Lammasu",
	types.Leech:                 "types.Leech",
	types.Lemur:                 "types.Lemur",
	types.Leviathan:             "types.Leviathan",
	types.Lhurgoyf:              "types.Lhurgoyf",
	types.Licid:                 "types.Licid",
	types.Lizard:                "types.Lizard",
	types.Lobster:               "types.Lobster",
	types.Manticore:             "types.Manticore",
	types.Masticore:             "types.Masticore",
	types.Mercenary:             "types.Mercenary",
	types.Merfolk:               "types.Merfolk",
	types.Metathran:             "types.Metathran",
	types.Minion:                "types.Minion",
	types.Minotaur:              "types.Minotaur",
	types.Mite:                  "types.Mite",
	types.Mole:                  "types.Mole",
	types.Monger:                "types.Monger",
	types.Mongoose:              "types.Mongoose",
	types.Monk:                  "types.Monk",
	types.Monkey:                "types.Monkey",
	types.Moogle:                "types.Moogle",
	types.Moonfolk:              "types.Moonfolk",
	types.Mount:                 "types.Mount",
	types.Mouse:                 "types.Mouse",
	types.Mutant:                "types.Mutant",
	types.Myr:                   "types.Myr",
	types.Mystic:                "types.Mystic",
	types.Nautilus:              "types.Nautilus",
	types.Necron:                "types.Necron",
	types.Nephilim:              "types.Nephilim",
	types.Nightmare:             "types.Nightmare",
	types.Nightstalker:          "types.Nightstalker",
	types.Ninja:                 "types.Ninja",
	types.Noble:                 "types.Noble",
	types.Noggle:                "types.Noggle",
	types.Nomad:                 "types.Nomad",
	types.Nymph:                 "types.Nymph",
	types.Octopus:               "types.Octopus",
	types.Ogre:                  "types.Ogre",
	types.Ooze:                  "types.Ooze",
	types.Orb:                   "types.Orb",
	types.Orc:                   "types.Orc",
	types.Orgg:                  "types.Orgg",
	types.Otter:                 "types.Otter",
	types.Ouphe:                 "types.Ouphe",
	types.Ox:                    "types.Ox",
	types.Oyster:                "types.Oyster",
	types.Pangolin:              "types.Pangolin",
	types.Peasant:               "types.Peasant",
	types.Pegasus:               "types.Pegasus",
	types.Pentavite:             "types.Pentavite",
	types.Performer:             "types.Performer",
	types.Pest:                  "types.Pest",
	types.Phelddagrif:           "types.Phelddagrif",
	types.Phoenix:               "types.Phoenix",
	types.Phyrexian:             "types.Phyrexian",
	types.Pilot:                 "types.Pilot",
	types.Pincher:               "types.Pincher",
	types.Pirate:                "types.Pirate",
	types.Plant:                 "types.Plant",
	types.Platypus:              "types.Platypus",
	types.Porcupine:             "types.Porcupine",
	types.Possum:                "types.Possum",
	types.Praetor:               "types.Praetor",
	types.Primarch:              "types.Primarch",
	types.Prism:                 "types.Prism",
	types.Processor:             "types.Processor",
	types.Qu:                    "types.Qu",
	types.Rabbit:                "types.Rabbit",
	types.Raccoon:               "types.Raccoon",
	types.Ranger:                "types.Ranger",
	types.Rat:                   "types.Rat",
	types.Rebel:                 "types.Rebel",
	types.Reflection:            "types.Reflection",
	types.Rhino:                 "types.Rhino",
	types.Rigger:                "types.Rigger",
	types.Robot:                 "types.Robot",
	types.Rogue:                 "types.Rogue",
	types.Sable:                 "types.Sable",
	types.Salamander:            "types.Salamander",
	types.Samurai:               "types.Samurai",
	types.Sand:                  "types.Sand",
	types.Saproling:             "types.Saproling",
	types.Satyr:                 "types.Satyr",
	types.Scarecrow:             "types.Scarecrow",
	types.Scientist:             "types.Scientist",
	types.Scion:                 "types.Scion",
	types.Scorpion:              "types.Scorpion",
	types.Scout:                 "types.Scout",
	types.Sculpture:             "types.Sculpture",
	types.Seal:                  "types.Seal",
	types.Serf:                  "types.Serf",
	types.Serpent:               "types.Serpent",
	types.Servo:                 "types.Servo",
	types.Shade:                 "types.Shade",
	types.Shaman:                "types.Shaman",
	types.Shapeshifter:          "types.Shapeshifter",
	types.Shark:                 "types.Shark",
	types.Sheep:                 "types.Sheep",
	types.Siren:                 "types.Siren",
	types.Skeleton:              "types.Skeleton",
	types.Skunk:                 "types.Skunk",
	types.Slith:                 "types.Slith",
	types.Sliver:                "types.Sliver",
	types.Sloth:                 "types.Sloth",
	types.Slug:                  "types.Slug",
	types.Snail:                 "types.Snail",
	types.Snake:                 "types.Snake",
	types.Soldier:               "types.Soldier",
	types.Soltari:               "types.Soltari",
	types.Sorcerer:              "types.Sorcerer",
	types.Spawn:                 "types.Spawn",
	types.Specter:               "types.Specter",
	types.Spellshaper:           "types.Spellshaper",
	types.Sphinx:                "types.Sphinx",
	types.Spider:                "types.Spider",
	types.Spike:                 "types.Spike",
	types.Spirit:                "types.Spirit",
	types.Splinter:              "types.Splinter",
	types.Sponge:                "types.Sponge",
	types.Squid:                 "types.Squid",
	types.Squirrel:              "types.Squirrel",
	types.Starfish:              "types.Starfish",
	types.Surrakar:              "types.Surrakar",
	types.Survivor:              "types.Survivor",
	types.Symbiote:              "types.Symbiote",
	types.Synth:                 "types.Synth",
	types.Tentacle:              "types.Tentacle",
	types.Tetravite:             "types.Tetravite",
	types.Thalakos:              "types.Thalakos",
	types.Thopter:               "types.Thopter",
	types.Thrull:                "types.Thrull",
	types.Tiefling:              "types.Tiefling",
	types.Toy:                   "types.Toy",
	types.Treefolk:              "types.Treefolk",
	types.Trilobite:             "types.Trilobite",
	types.Triskelavite:          "types.Triskelavite",
	types.Troll:                 "types.Troll",
	types.Turtle:                "types.Turtle",
	types.Tyranid:               "types.Tyranid",
	types.Unicorn:               "types.Unicorn",
	types.Utrom:                 "types.Utrom",
	types.Vampire:               "types.Vampire",
	types.Varmint:               "types.Varmint",
	types.Vedalken:              "types.Vedalken",
	types.Villain:               "types.Villain",
	types.Volver:                "types.Volver",
	types.Wall:                  "types.Wall",
	types.Walrus:                "types.Walrus",
	types.Warlock:               "types.Warlock",
	types.Warrior:               "types.Warrior",
	types.Weasel:                "types.Weasel",
	types.Weird:                 "types.Weird",
	types.Werewolf:              "types.Werewolf",
	types.Whale:                 "types.Whale",
	types.Wizard:                "types.Wizard",
	types.Wolf:                  "types.Wolf",
	types.Wolverine:             "types.Wolverine",
	types.Wombat:                "types.Wombat",
	types.Worm:                  "types.Worm",
	types.Wraith:                "types.Wraith",
	types.Wurm:                  "types.Wurm",
	types.Yeti:                  "types.Yeti",
	types.Zombie:                "types.Zombie",
	types.Zubera:                "types.Zubera",
	types.Undercity:             "types.Undercity",
	types.Aura:                  "types.Aura",
	types.Background:            "types.Background",
	types.Cartouche:             "types.Cartouche",
	types.Case:                  "types.Case",
	types.Class:                 "types.Class",
	types.Curse:                 "types.Curse",
	types.Role:                  "types.Role",
	types.Room:                  "types.Room",
	types.Rune:                  "types.Rune",
	types.Saga:                  "types.Saga",
	types.Shard:                 "types.Shard",
	types.Shrine:                "types.Shrine",
	types.Cave:                  "types.Cave",
	types.Desert:                "types.Desert",
	types.Forest:                "types.Forest",
	types.Gate:                  "types.Gate",
	types.Island:                "types.Island",
	types.Lair:                  "types.Lair",
	types.Locus:                 "types.Locus",
	types.Mine:                  "types.Mine",
	types.Mountain:              "types.Mountain",
	types.Plains:                "types.Plains",
	types.Planet:                "types.Planet",
	types.PowerPlant:            "types.PowerPlant",
	types.Sphere:                "types.Sphere",
	types.Swamp:                 "types.Swamp",
	types.Tower:                 "types.Tower",
	types.Town:                  "types.Town",
	types.Urzas:                 "types.Urzas",
	types.TheAbyss:              "types.TheAbyss",
	types.Alara:                 "types.Alara",
	types.AlfavaMetraxis:        "types.AlfavaMetraxis",
	types.Amonkhet:              "types.Amonkhet",
	types.AndrozaniMinor:        "types.AndrozaniMinor",
	types.Antausia:              "types.Antausia",
	types.Apalapucia:            "types.Apalapucia",
	types.Arcavios:              "types.Arcavios",
	types.Arkhos:                "types.Arkhos",
	types.Avishkar:              "types.Avishkar",
	types.Azgol:                 "types.Azgol",
	types.Belenon:               "types.Belenon",
	types.BolassMeditationRealm: "types.BolassMeditationRealm",
	types.Capenna:               "types.Capenna",
	types.Cridhe:                "types.Cridhe",
	types.TheDalekAsylum:        "types.TheDalekAsylum",
	types.Darillium:             "types.Darillium",
	types.Dominaria:             "types.Dominaria",
	types.Earth:                 "types.Earth",
	types.Echoir:                "types.Echoir",
	types.Eldraine:              "types.Eldraine",
	types.Equilor:               "types.Equilor",
	types.Ergamon:               "types.Ergamon",
	types.Fabacin:               "types.Fabacin",
	types.Fiora:                 "types.Fiora",
	types.Gallifrey:             "types.Gallifrey",
	types.Gargantikar:           "types.Gargantikar",
	types.Gobakhan:              "types.Gobakhan",
	types.HorseheadNebula:       "types.HorseheadNebula",
	types.Ikoria:                "types.Ikoria",
	types.Innistrad:             "types.Innistrad",
	types.Iquatana:              "types.Iquatana",
	types.Ir:                    "types.Ir",
	types.Ixalan:                "types.Ixalan",
	types.Kaldheim:              "types.Kaldheim",
	types.Kamigawa:              "types.Kamigawa",
	types.Kandoka:               "types.Kandoka",
	types.Karsus:                "types.Karsus",
	types.Kephalai:              "types.Kephalai",
	types.Kinshala:              "types.Kinshala",
	types.Kolbahan:              "types.Kolbahan",
	types.Kylem:                 "types.Kylem",
	types.Kyneth:                "types.Kyneth",
	types.TheLibrary:            "types.TheLibrary",
	types.Lorwyn:                "types.Lorwyn",
	types.Luvion:                "types.Luvion",
	types.Mars:                  "types.Mars",
	types.Mercadia:              "types.Mercadia",
	types.Mirrodin:              "types.Mirrodin",
	types.Moag:                  "types.Moag",
	types.Mongseng:              "types.Mongseng",
	types.Moon:                  "types.Moon",
	types.Muraganda:             "types.Muraganda",
	types.Necros:                "types.Necros",
	types.NewEarth:              "types.NewEarth",
	types.NewPhyrexia:           "types.NewPhyrexia",
	types.OutsideMuttersSpiral:  "types.OutsideMuttersSpiral",
	types.Phyrexia:              "types.Phyrexia",
	types.Pyrulea:               "types.Pyrulea",
	types.Rabiah:                "types.Rabiah",
	types.Rath:                  "types.Rath",
	types.Ravnica:               "types.Ravnica",
	types.Regatha:               "types.Regatha",
	types.Segovia:               "types.Segovia",
	types.SerrasRealm:           "types.SerrasRealm",
	types.Shadowmoor:            "types.Shadowmoor",
	types.Shandalar:             "types.Shandalar",
	types.Shenmeng:              "types.Shenmeng",
	types.Skaro:                 "types.Skaro",
	types.Tarkir:                "types.Tarkir",
	types.Theros:                "types.Theros",
	types.Time:                  "types.Time",
	types.Trenzalore:            "types.Trenzalore",
	types.Ulgrotha:              "types.Ulgrotha",
	types.UnknownPlanet:         "types.UnknownPlanet",
	types.Valla:                 "types.Valla",
	types.Vryn:                  "types.Vryn",
	types.Wildfire:              "types.Wildfire",
	types.Xerex:                 "types.Xerex",
	types.Zendikar:              "types.Zendikar",
	types.Zhalfir:               "types.Zhalfir",
	types.Ajani:                 "types.Ajani",
	types.Aminatou:              "types.Aminatou",
	types.Angrath:               "types.Angrath",
	types.Arlinn:                "types.Arlinn",
	types.Ashiok:                "types.Ashiok",
	types.Bahamut:               "types.Bahamut",
	types.Basri:                 "types.Basri",
	types.Bolas:                 "types.Bolas",
	types.Calix:                 "types.Calix",
	types.Chandra:               "types.Chandra",
	types.Comet:                 "types.Comet",
	types.Dack:                  "types.Dack",
	types.Dakkon:                "types.Dakkon",
	types.Daretti:               "types.Daretti",
	types.Davriel:               "types.Davriel",
	types.Dellian:               "types.Dellian",
	types.Dihada:                "types.Dihada",
	types.Domri:                 "types.Domri",
	types.Dovin:                 "types.Dovin",
	types.Ellywick:              "types.Ellywick",
	types.Elminster:             "types.Elminster",
	types.Elspeth:               "types.Elspeth",
	types.Estrid:                "types.Estrid",
	types.Freyalise:             "types.Freyalise",
	types.Garruk:                "types.Garruk",
	types.Gideon:                "types.Gideon",
	types.Grist:                 "types.Grist",
	types.Guff:                  "types.Guff",
	types.Huatli:                "types.Huatli",
	types.Jace:                  "types.Jace",
	types.Jared:                 "types.Jared",
	types.Jaya:                  "types.Jaya",
	types.Jeska:                 "types.Jeska",
	types.Kaito:                 "types.Kaito",
	types.Karn:                  "types.Karn",
	types.Kasmina:               "types.Kasmina",
	types.Kaya:                  "types.Kaya",
	types.Kiora:                 "types.Kiora",
	types.Koth:                  "types.Koth",
	types.Liliana:               "types.Liliana",
	types.Lolth:                 "types.Lolth",
	types.Lukka:                 "types.Lukka",
	types.Minsc:                 "types.Minsc",
	types.Mordenkainen:          "types.Mordenkainen",
	types.Nahiri:                "types.Nahiri",
	types.Narset:                "types.Narset",
	types.Niko:                  "types.Niko",
	types.Nissa:                 "types.Nissa",
	types.Nixilis:               "types.Nixilis",
	types.Oko:                   "types.Oko",
	types.Quintorius:            "types.Quintorius",
	types.Ral:                   "types.Ral",
	types.Rowan:                 "types.Rowan",
	types.Saheeli:               "types.Saheeli",
	types.Samut:                 "types.Samut",
	types.Sarkhan:               "types.Sarkhan",
	types.Serra:                 "types.Serra",
	types.Sivitri:               "types.Sivitri",
	types.Sorin:                 "types.Sorin",
	types.Szat:                  "types.Szat",
	types.Tamiyo:                "types.Tamiyo",
	types.Tasha:                 "types.Tasha",
	types.Teferi:                "types.Teferi",
	types.Teyo:                  "types.Teyo",
	types.Tezzeret:              "types.Tezzeret",
	types.Tibalt:                "types.Tibalt",
	types.Tyvar:                 "types.Tyvar",
	types.Ugin:                  "types.Ugin",
	types.Urza:                  "types.Urza",
	types.Venser:                "types.Venser",
	types.Vivien:                "types.Vivien",
	types.Vraska:                "types.Vraska",
	types.Vronos:                "types.Vronos",
	types.Will:                  "types.Will",
	types.Windgrace:             "types.Windgrace",
	types.Wrenn:                 "types.Wrenn",
	types.Xenagos:               "types.Xenagos",
	types.Yanggu:                "types.Yanggu",
	types.Yanling:               "types.Yanling",
	types.Zariel:                "types.Zariel",
	types.Adventure:             "types.Adventure",
	types.Arcane:                "types.Arcane",
	types.Lesson:                "types.Lesson",
	types.Omen:                  "types.Omen",
	types.Trap:                  "types.Trap",
}

// typesSuperLiterals maps each exported types.Super constant to the Go
// expression that names it in generated card source.
var typesSuperLiterals = map[types.Super]string{
	types.Legendary: "types.Legendary",
	types.Basic:     "types.Basic",
	types.Snow:      "types.Snow",
	types.World:     "types.World",
	types.Ongoing:   "types.Ongoing",
	types.Host:      "types.Host",
}

// zoneTypeLiterals maps each exported zone.Type constant to the Go
// expression that names it in generated card source.
var zoneTypeLiterals = map[zone.Type]string{
	zone.None:        "zone.None",
	zone.Library:     "zone.Library",
	zone.Hand:        "zone.Hand",
	zone.Battlefield: "zone.Battlefield",
	zone.Graveyard:   "zone.Graveyard",
	zone.Stack:       "zone.Stack",
	zone.Exile:       "zone.Exile",
	zone.Command:     "zone.Command",
}
