// Code generated by compilecards; DO NOT EDIT.

package m

import "github.com/natefinch/council4/mtg/game"

// Cards lists all card definitions in this package.
var Cards = []*game.CardDef{
	MaritLageToken48e9147e59f7469383d77f514be871bc,
	MerfolkToken23f86e9302034222b78a8f1c9fa16394,
	MerfolkToken4998e2fe153740bba4d7f668a5b8975f,
	MerfolkTokenfd6663bc49ae4e31b0aa60f142dfd18c,
	MerfolkWizardToken224debbd60734455accfbcf3c9674c72,
	MetallicSliverToken7cf70a6b6b55400c9a89b4b85f7a19f5,
	MinionToken62738f7a19874e6ca7fc638ef6aaef13,
	MinotaurToken6b8117bf384f4f5e9e52e01412ce24a9,
	MonkToken026e1dbbbbe44164af19262a85f4a69d,
	MonkTokenbfa57f61381143dab73e90e3e5b0b2c2,
	MoogleToken14f83370fb60453a993ac3aaa8565f16,
	MoonfolkTokenfdbd24ef7d3f4af7a273cc58de7cfb97,
	MouseToken94bc231d49a344e0b79781a6e6961bbd,
	MowuTokenf425d9db08e94f069b082a5804d4f0fd,
	MutantToken9abddb215b244cf788788b87e6ecbc65,
	MutantTokenb0bae19e98ff4714af04f4262ca57c50,
	MyrToken21711b3c2f1e47b69d9b979be78df2eb,
	MyrTokenbf690282125f431ca36339f6772324c8,
}
