// Code generated by compilecards; DO NOT EDIT.

package o

import "github.com/natefinch/council4/mtg/game"

// Cards lists all card definitions in this package.
var Cards = []*game.CardDef{
	OctopusToken0ca71a088a2d4b0aa17485cd7d2f36b6,
	OgreToken99ba3fcefab441a9a215fc3b8ece122c,
	OgreTokene42753ba6c5940d19fb54282dcc4b14f,
	OgreWarriorToken77fc8f50dcf14d608fd6b1c7d58a9724,
	OketraSAttendantToken422b060deb90440697b728943a426c83,
	OozeToken48bf958891fa4f4ca93a3bef29ac9c27,
	OozeToken54a41f403409481f8ad4dfb939f6c7a9,
	OozeToken6d0b29d44d4b4307977827c7483cbcb8,
	OozeTokenbb3da6d2aed74057b94b6882fb45cc89,
	OozeTokenee54f59ea3344f0d8bc644fb97c948ac,
	OrcArmyToken620159f8eb7f4756a1368ad9728adbad,
	OrnithopterToken75336d5252784e989875b3ac8b91bfe2,
	OtterToken6c1bb10eb0834978ab0a6f6a6b5bcf2c,
	OxTokenbcb63395fec24792bb4e2c3e9b4703b4,
	OxTokend82356994c2c4cf1815ad2a1c01b0cae,
	OxTokenf7b5b479a0734d8ab6542d0d0f6ecf83,
}
