package game

import (
	"github.com/natefinch/council4/mtg/game/color"
	"github.com/natefinch/council4/mtg/game/id"
	"github.com/natefinch/council4/mtg/game/zone"
)

// StackObjectKind classifies what kind of object is on the stack.
type StackObjectKind int

const (
	// StackSpell is a spell being cast (instant, sorcery, or permanent spell).
	StackSpell StackObjectKind = iota

	// StackActivatedAbility is an activated ability on the stack.
	StackActivatedAbility

	// StackTriggeredAbility is a triggered ability on the stack.
	StackTriggeredAbility
)

// StackObject represents a spell or ability on the stack waiting to resolve.
// The stack resolves last-in, first-out (LIFO).
type StackObject struct {
	// ID is the unique identifier for this stack object.
	ID id.ID

	// Kind classifies this as a spell, activated ability, or triggered ability.
	Kind StackObjectKind

	// SourceID is the CardInstance ID for card-backed spells and hand-zone
	// activated abilities, or the Permanent's ObjectID for battlefield
	// activated/triggered abilities and spells copied from token permanents.
	SourceID id.ID

	// Face is the selected spell face or the source face captured when an
	// ability was put on the stack.
	Face FaceIndex

	// SourceCardID is the source CardInstance ID for activated/triggered
	// abilities when it is known. It lets ability resolution preserve source
	// identity even if the source permanent has left the battlefield.
	SourceCardID id.ID

	// SourceTokenDef is the source definition for token abilities, which have
	// no source CardInstance ID.
	SourceTokenDef *CardDef

	// AbilityIndex identifies the source ability for activated/triggered
	// abilities. It is ignored for spells.
	AbilityIndex int

	// InlineTrigger stores generated triggered abilities (delayed triggers, ward
	// triggers, prowess, exalted, madness) that are not addressable by AbilityIndex
	// on the source definition.
	InlineTrigger *TriggeredAbility

	// InlineActivated and InlineLoyalty preserve effective abilities that are
	// not addressable on the top card definition, including abilities inherited
	// from lower cards in a merged permanent.
	InlineActivated *ActivatedAbility
	InlineLoyalty   *LoyaltyAbility

	// SagaChapter identifies an inline triggered ability generated by a Saga
	// chapter.
	SagaChapter bool

	// TriggerEvent is the event that caused this triggered ability to trigger.
	// HasTriggerEvent distinguishes a real zero-valued event from no event.
	TriggerEvent    Event
	HasTriggerEvent bool

	// WardTargetStackObjectID is the spell or ability a Ward trigger may
	// counter unless its controller pays the Ward cost.
	WardTargetStackObjectID id.ID

	// Controller is the player who controls this spell or ability.
	Controller PlayerID

	// Targets are the chosen runtime targets (permanents, players, etc.).
	// Targets are locked in when the spell/ability is put on the stack
	// (CR 601.2c, 603.3d).
	Targets []Target

	// TargetCounts records how many runtime targets were chosen for each
	// TargetSpec, preserving mode-local target indexing during resolution.
	TargetCounts []int

	// ChosenModes are the indices of chosen modes for modal spells/abilities.
	ChosenModes []int

	// RuleEffects are object-local rules effects created while this spell was
	// cast, such as "that spell can't be countered" from mana spent to cast it.
	RuleEffects []RuleEffect

	// XValue is the chosen value of X for spells with {X} in their cost.
	XValue int

	// ColorsOfManaSpentToCast is the number of distinct colors of mana spent to
	// cast this spell, recorded as its costs are paid (CR 202.2, CR 702.76). It
	// backs the Converge count ("for each color of mana spent to cast it"),
	// including the enters-with-counters quantity on the resulting permanent,
	// where the synthetic enter-the-battlefield object carries it forward from
	// the spell's creation options. Colorless mana contributes no color, so it
	// is zero for a spell paid entirely with colorless or generic-from-colorless
	// mana.
	ColorsOfManaSpentToCast int

	// ManaSpentByColorToCast records, per color, how much colored mana was spent
	// to cast this spell, recorded as its costs are paid (CR 202.2). It backs the
	// Adamant ability word's "at least three <color> mana was spent to cast this
	// spell" and "at least three mana of the same color" predicates (CR 702.132),
	// which the synthetic enter-the-battlefield object carries forward from the
	// spell's creation options. Colorless and generic-from-colorless mana
	// contribute no entry, so it is nil for a spell paid entirely with such mana.
	ManaSpentByColorToCast map[color.Color]int

	// ManaSpentToCast is the total amount of mana spent to cast this spell,
	// recorded as its costs are paid (CR 202.3, CR 601.2h). It backs Mockingbird's
	// "with mana value less than or equal to the amount of mana spent to cast this
	// creature", which the synthetic enter-the-battlefield object carries forward
	// to bound the copiable permanents. It is zero for a spell that spent no mana
	// (a free cast) and for a permanent that was not cast.
	ManaSpentToCast int

	// KickerPaid is true if the kicker cost was paid.
	KickerPaid bool

	// KickerCount is the number of times the kicker cost was paid as the spell
	// was cast (CR 702.32). For Multikicker it can exceed one; for ordinary
	// Kicker it is zero (KickerPaid carries the paid-once state). It scales
	// "for each time it was kicked" amounts as the spell resolves.
	KickerCount int

	// GiftPromised is true if this spell's Gift keyword action promised a gift to
	// an opponent as it was cast (CR 702.171). It gates the spell's "if the gift
	// was promised" clauses and drives the gift delivery on resolution. A copy of
	// a promised spell inherits the promise to the same opponent (CR 707.10).
	GiftPromised bool

	// GiftRecipient is the opponent promised the gift when GiftPromised is true.
	// The gift is delivered to this player before the spell's other effects.
	GiftRecipient PlayerID

	// Overloaded is true if this spell was cast for its overload cost.
	Overloaded bool

	// Evoked is true if this spell was cast for its Evoke alternative cost
	// (CR 702.74); the resulting permanent is sacrificed when it enters.
	Evoked bool

	// Converted is true if this spell was cast for its "More Than Meets the Eye"
	// alternative cost (CR 712); the resulting permanent enters the battlefield
	// converted, as its back face.
	Converted bool

	// Dashed is true if this spell was cast for its Dash alternative cost
	// (CR 702.109); the resulting permanent gains haste and is returned to its
	// owner's hand at the beginning of the next end step.
	Dashed bool

	// Mutate records an alternative-cost creature spell and the permanent it
	// will merge with.
	Mutate         bool
	MutateTargetID id.ID

	// Flashback is true if this spell was cast from a graveyard using
	// flashback; it is exiled if it would leave the stack (CR 702.34).
	Flashback bool

	// CastDuringControllerMainPhase records whether this spell was cast while
	// its controller was the active player and the game was in a main phase. It
	// feeds the Addendum cast-timing condition at resolution.
	CastDuringControllerMainPhase bool

	// ExileOnResolution is set by a resolving self-exile instruction. A
	// non-copy instant or sorcery moves to exile instead of its normal
	// graveyard destination after its remaining instructions resolve.
	ExileOnResolution bool

	// CounteredDestination redirects this spell's card to a zone other than its
	// owner's graveyard when it is countered, backing the CR 614-style
	// replacement "If that spell is countered this way, put it [on top of its
	// owner's library | into its owner's hand] instead of into that player's
	// graveyard." The zero value leaves a countered spell in its owner's
	// graveyard. It is mutually exclusive with ExileOnResolution.
	CounteredDestination CounteredSpellDestination

	// ShuffleIntoLibraryOnResolution is set by a resolving self-shuffle
	// instruction. A non-copy instant or sorcery is shuffled into its owner's
	// library instead of its normal graveyard destination after its remaining
	// instructions resolve (Green Sun's Zenith, the Beacon cycle).
	ShuffleIntoLibraryOnResolution bool

	// Suspend is true if this spell was cast from exile by suspend.
	Suspend bool

	// GainsKeywordsUntilEndOfTurn are keyword abilities a mana-spend rider
	// granted to this creature spell when its tagged mana was spent (Arena of
	// Glory, Generator Servant: "it gains haste until end of turn"). They are
	// applied as a layer-ability continuous effect to the resolved permanent and
	// expire at end of turn.
	GainsKeywordsUntilEndOfTurn []Keyword

	// FaceDown is true if this spell was cast face-down via Morph or Disguise.
	FaceDown bool

	// FaceDownFace records the printed face hidden under a face-down spell.
	// It is ignored unless FaceDown is true.
	FaceDownFace FaceIndex

	// FaceDownKind records whether this spell was cast face-down by Morph,
	// Disguise, or a future face-down mechanic.
	FaceDownKind FaceDownKind

	// Copy is true if this stack object is a copy of a spell rather than the
	// physical source card.
	Copy bool

	// AdditionalCostsPaid describes any additional costs that were paid
	// (e.g., "sacrificed a creature", "discarded a card").
	AdditionalCostsPaid []string

	// SacrificedAsCostIDs are the object IDs of permanents sacrificed to pay
	// this ability's activation cost. They let an effect read the sacrificed
	// permanent through last-known information ("the sacrificed creature's
	// power"). Empty when no permanent was sacrificed as a cost.
	SacrificedAsCostIDs []id.ID

	// ExiledAsCostIDs are the card-instance IDs of cards exiled from a zone to
	// pay this ability's activation cost (e.g. "Exile two creature cards from
	// your graveyard"). They let a resolution effect act on the cost-exiled
	// cards ("An opponent chooses one of the exiled cards ..."). Empty when no
	// card was exiled as a cost.
	ExiledAsCostIDs []id.ID

	// SourceZone is the zone the source card occupied before this spell or
	// ability was put on the stack.
	SourceZone zone.Type

	// SourceZoneVersion identifies the source card incarnation that created
	// this stack object.
	SourceZoneVersion uint64

	// Ninjutsu marks a hand activation that puts its source onto the battlefield
	// tapped and attacking NinjutsuAttackTarget as it resolves.
	Ninjutsu             bool
	NinjutsuAttackTarget AttackTarget

	// ResolvedAmounts stores named numeric results from earlier effects on this
	// stack object for "that much" style follow-up effects.
	ResolvedAmounts map[string]int

	// ResolvedExcessDamage stores named excess-damage results from earlier
	// damage effects on this stack object.
	ResolvedExcessDamage map[string]int

	// ResolutionResults stores named success/choice results from earlier
	// instructions on this stack object for "if you do" / "if you don't" branches.
	ResolutionResults map[string]InstructionResolutionResult

	// ResolutionChoices stores named values chosen while resolving this stack
	// object, for later instructions such as "of the chosen color" (CR 608.2c).
	ResolutionChoices map[string]ResolutionChoiceResult

	// TargetControllerLKI preserves the controller of a targeted stack object
	// after an earlier instruction removes it from the stack.
	TargetControllerLKI map[int]PlayerID
	// TargetManaValueLKI preserves the mana value of a targeted spell after an
	// earlier instruction removes it from the stack.
	TargetManaValueLKI map[int]int

	// CapturedTargetControllerLKI preserves controllers captured from the
	// enclosing spell or ability that created a delayed trigger.
	CapturedTargetControllerLKI map[int]PlayerID
	// CapturedTargetManaValueLKI preserves target spell mana values captured
	// from the enclosing spell or ability that created a delayed trigger.
	CapturedTargetManaValueLKI map[int]int

	// CapturedObjectID is the permanent frozen at schedule time by the delayed
	// trigger that produced this stack object, carried so content referencing
	// ObjectReferenceCapturedObject can act on the combat creature after the
	// triggering combat event is gone ("destroy that creature at end of
	// combat").
	CapturedObjectID id.ID
	// CapturedObjectIDs are the permanents frozen at schedule time by the delayed
	// trigger that produced this stack object, carried so content referencing
	// GroupDomainCapturedObjects (CapturedObjectsGroup) can act on the whole set
	// after the linked key that named them may have been reused ("Exile the
	// tokens at end of combat.", the myriad keyword).
	CapturedObjectIDs []id.ID
}

// Stack represents the game stack — the zone where spells and abilities
// wait to resolve in last-in, first-out (LIFO) order (CR 405).
type Stack struct {
	objects []*StackObject
}

// Push adds an object to the top of the stack.
func (s *Stack) Push(obj *StackObject) {
	s.objects = append(s.objects, obj)
}

// Pop removes and returns the top object from the stack.
func (s *Stack) Pop() (*StackObject, bool) {
	if len(s.objects) == 0 {
		return nil, false
	}
	top := s.objects[len(s.objects)-1]
	s.objects = s.objects[:len(s.objects)-1]
	return top, true
}

// Peek returns the top object without removing it.
func (s *Stack) Peek() (*StackObject, bool) {
	if len(s.objects) == 0 {
		return nil, false
	}
	top := s.objects[len(s.objects)-1]
	return top, true
}

// RemoveByID removes and returns the stack object with the given ID.
func (s *Stack) RemoveByID(objectID id.ID) (*StackObject, bool) {
	for i, obj := range s.objects {
		if obj.ID != objectID {
			continue
		}
		s.objects = append(s.objects[:i], s.objects[i+1:]...)
		return obj, true
	}
	return nil, false
}

// IsEmpty reports whether the stack has no objects.
func (s *Stack) IsEmpty() bool {
	return len(s.objects) == 0
}

// Size returns the number of objects on the stack.
func (s *Stack) Size() int {
	return len(s.objects)
}

// Objects returns a copy of all objects on the stack, from bottom to top.
func (s *Stack) Objects() []*StackObject {
	result := make([]*StackObject, len(s.objects))
	copy(result, s.objects)
	return result
}

// RemoveControlledBy removes stack objects controlled by playerID.
func (s *Stack) RemoveControlledBy(playerID PlayerID) {
	kept := s.objects[:0]
	for _, obj := range s.objects {
		if obj.Controller == playerID {
			continue
		}
		kept = append(kept, obj)
	}
	s.objects = kept
}
