// Code generated by gencardlist; DO NOT EDIT.

package b

import "github.com/natefinch/council4/mtg/game"

// Cards lists all card definitions in this package.
var Cards = []*game.CardDef{
	BackForMore,
	BalustradeSpy,
	BasiliskCollar,
	BaskingBroodscale,
	BattleStrain,
	BeastWithin,
	BeastriderVanguard,
	BelligerentHatchling,
	Bereavement,
	BirdsOfParadise,
	BiteDown,
	BlazemireVerge,
	BlazingSunsteel,
	BleedDry,
	BlitzOfTheThunderRaptor,
	BloodletterQuill,
	BoardTheWeatherlight,
	BolasSCitadel,
	BoneHarvest,
	BoromirGondorSHope,
	BotBashingTime,
	BragoKingEternal,
	BrassTalonChimera,
	BrazenUpstart,
	BridgeworksBattle,
	BrightwoodTracker,
	BrokersHideout,
	BuckyBarnesEagerAlly,
	BugenhagenWiseElder,
	BurnTheAccursed,
	Bushwhack,
}
