// Code generated by gencardlist; DO NOT EDIT.

package b

import "github.com/natefinch/council4/mtg/game"

// Cards lists all card definitions in this package.
var Cards = []*game.CardDef{
	BackForMore,
	BalustradeSpy,
	BasiliskCollar,
	BaskingBroodscale,
	BattleStrain,
	BeastWithin,
	BelligerentHatchling,
	Bereavement,
	BirdsOfParadise,
	BiteDown,
	BlazemireVerge,
	BlazingSunsteel,
	BleedDry,
	BlitzOfTheThunderRaptor,
	BloodletterQuill,
	BolasSCitadel,
	BoneHarvest,
	BotBashingTime,
	BragoKingEternal,
	BridgeworksBattle,
	BrokersHideout,
	BugenhagenWiseElder,
	BurnTheAccursed,
	Bushwhack,
}
