// Code generated by gencardlist; DO NOT EDIT.

package b

import "github.com/natefinch/council4/mtg/game"

// Cards lists all card definitions in this package.
var Cards = []*game.CardDef{
	BasiliskCollar,
	BeastWithin,
	BirdsOfParadise,
	BiteDown,
	BlazemireVerge,
	BlazingSunsteel,
	BridgeworksBattle,
	BugenhagenWiseElder,
	Bushwhack,
}
