// Code generated by gencardlist; DO NOT EDIT.

package s

import "github.com/natefinch/council4/mtg/game"

// Cards lists all card definitions in this package.
var Cards = []*game.CardDef{
	SalvationSwan,
	SavageSmash,
	ScorchingDragonfire,
	Scorchmark,
	ServoSchematic,
	SetessanTraining,
	ShatteredCrypt,
	ShedWeakness,
	ShelteredByGhosts,
	ShriekingSpecter,
	SilkweaverElite,
	Skeletonize,
	SkitteringPrecursor,
	SkyriderElf,
	SlateStreetRuffian,
	SludgeTitan,
	SmiteTheDeathless,
	SolemnRecruit,
	SpawnbedProtector,
	SphinxMindbreaker,
	SphinxOfUthuun,
	SpiderSpawning,
	SpringmantleCleric,
	SteamAugury,
	SturdyHatchling,
	SunDroplet,
	SwiftKick,
}
