// Code generated by gencardlist; DO NOT EDIT.

package c

import "github.com/natefinch/council4/mtg/game"

// Cards lists all card definitions in this package.
var Cards = []*game.CardDef{
	CaribouRange,
	CartoucheOfAmbition,
	CartoucheOfKnowledge,
	CartoucheOfSolidarity,
	CartoucheOfZeal,
	ChainedToTheRocks,
	ChainsOfCustody,
	ChandraSIgnition,
	ChaosWarp,
	ChelonianTackle,
	CinderGlade,
	CliveSHideaway,
	CommandTower,
	ContestOfClaws,
	CosmicHunger,
	CountlessGearsRenegade,
	CrystallineCrawler,
	CurseOfTheSwine,
}
