// Code generated by gencardlist; DO NOT EDIT.

package u

import "github.com/natefinch/council4/mtg/game"

// Cards lists all card definitions in this package.
var Cards = []*game.CardDef{
	UncoveredClues,
	UndercityInformer,
	UneshCriosphinxSovereign,
	UnfathomableTruths,
	UnsparingBoltcaster,
	UntimelyMalfunction,
	UreniOfTheUnwritten,
	UrsineFylgja,
	UrzaPrinceOfKroog,
	UtopiaMycon,
	UrzaSChalice,
	UtopiaMycon,
	UtromScientists,
}
