// Code generated by gencardlist; DO NOT EDIT.

package u

import "github.com/natefinch/council4/mtg/game"

// Cards lists all card definitions in this package.
var Cards = []*game.CardDef{
	UginSInsight,
	UltrosObnoxiousOctopus,
	UmezawaSJitte,
	UncoveredClues,
	UndercityInformer,
	UndercitySEmbrace,
	UneshCriosphinxSovereign,
	UnexplainedVision,
	UnfathomableTruths,
	UnleashFury,
	UnshakableTail,
	UnsparingBoltcaster,
	UnstableMutation,
	UntamedKavu,
	UntimelyMalfunction,
	UnwillingRecruit,
	UrborgMindsucker,
	UrborgSkeleton,
	UreniOfTheUnwritten,
	UrsineFylgja,
	UrzaPrinceOfKroog,
	UrzaSArmor,
	UrzaSBauble,
	UtopiaMycon,
	UrzaSChalice,
	UrzaSRage,
	UtopiaMycon,
	UtromScientists,
	UtterInsignificance,
	UnholyHunger,
}
