// Code generated by gencardlist; DO NOT EDIT.

package o

import "github.com/natefinch/council4/mtg/game"

// Cards lists all card definitions in this package.
var Cards = []*game.CardDef{
	OakhameAdversary,
	Oasis,
	OathOfChandra,
	OathOfLiliana,
	ObNixilisSCruelty,
	ObliteratingBolt,
	ObscuraStorefront,
	OgreSiegebreaker,
	OminousRoost,
	OnduWarCleric,
	OnyxTalisman,
	OonaSBlackguard,
	OperaLoveSong,
	Opportunist,
	OrcGeneral,
	OrchardWarden,
	OrderOfTheStars,
	OrdruunCommando,
	OrimSamiteHealer,
	OrneryGoblin,
	OsaiVultures,
	OtherworldlyJourney,
	OvergrownPest,
	OviyaPashiriSageLifecrafter,
}
