// Code generated by gencardlist; DO NOT EDIT.

package o

import "github.com/natefinch/council4/mtg/game"

// Cards lists all card definitions in this package.
var Cards = []*game.CardDef{
	Oasis,
	ObNixilisSCruelty,
	ObliteratingBolt,
	ObscuraStorefront,
	OminousRoost,
	OnduWarCleric,
	OperaLoveSong,
	OrcGeneral,
	OrdruunCommando,
	OrimSamiteHealer,
	OrderOfTheStars,
	OrneryGoblin,
	OsaiVultures,
	OtherworldlyJourney,
	OvergrownPest,
}
