// Code generated by compilecards; DO NOT EDIT.

package l

import "github.com/natefinch/council4/mtg/game"

// Cards lists all card definitions in this package.
var Cards = []*game.CardDef{
	LaserbeakTokencf1146f167604d1380bc7731e1c62e4d,
	LizardToken150fe7d9a31d494791a270ddebefa95d,
	LizardToken49db8af8de3b4503acc604cac2f87a2e,
	LlanowarElvesTokeneaddc7cf5d58422aba006708dee2d853,
}
