// Code generated by gencardlist; DO NOT EDIT.

package a

import "github.com/natefinch/council4/mtg/game"

// Cards lists all card definitions in this package.
var Cards = []*game.CardDef{
	AbyssalNightstalker,
	AcclaimedContender,
	AdaptiveOmnitool,
	AdventurousImpulse,
	AetherShockwave,
	AirdropAeronauts,
	AjaniSInfluence,
	AkromaSDevoted,
	AllIsDust,
	AlleyGrifters,
	AnabaSpiritCrafter,
	AncientStirrings,
	AngelicSellSword,
	Anger,
	AnkhOfMishra,
	ArcaneInfusion,
	ArcanistSOwl,
	ArdenvalePaladin,
	Arena,
	ArmorThrull,
	AshePrincessOfDalmasca,
	AspectOfLamprey,
	AugurOfBolas,
	AvacynianPriest,
}
