// Code generated by gencardlist; DO NOT EDIT.

package a

import "github.com/natefinch/council4/mtg/game"

// Cards lists all card definitions in this package.
var Cards = []*game.CardDef{
	AirdropAeronauts,
	AllIsDust,
	Anger,
	AnkhOfMishra,
	Arena,
	AspectOfLamprey,
}
