// Code generated by gencardlist; DO NOT EDIT.

package a

import "github.com/natefinch/council4/mtg/game"

// Cards lists all card definitions in this package.
var Cards = []*game.CardDef{
	AbyssalNightstalker,
	AirdropAeronauts,
	AkromaSDevoted,
	AllIsDust,
	AlleyGrifters,
	AnabaSpiritCrafter,
	AngelicSellSword,
	Anger,
	AnkhOfMishra,
	Arena,
	ArmorThrull,
	AspectOfLamprey,
}
