// Code generated by compilecards; DO NOT EDIT.

// Package tokens provides playable token definitions.
package tokens

import (
	"slices"

	"github.com/natefinch/council4/mtg/cards/tokens/a"
	"github.com/natefinch/council4/mtg/cards/tokens/b"
	"github.com/natefinch/council4/mtg/cards/tokens/c"
	"github.com/natefinch/council4/mtg/cards/tokens/d"
	"github.com/natefinch/council4/mtg/cards/tokens/e"
	"github.com/natefinch/council4/mtg/cards/tokens/f"
	"github.com/natefinch/council4/mtg/cards/tokens/g"
	"github.com/natefinch/council4/mtg/cards/tokens/h"
	"github.com/natefinch/council4/mtg/cards/tokens/i"
	"github.com/natefinch/council4/mtg/cards/tokens/k"
	"github.com/natefinch/council4/mtg/cards/tokens/l"
	"github.com/natefinch/council4/mtg/cards/tokens/m"
	"github.com/natefinch/council4/mtg/cards/tokens/n"
	"github.com/natefinch/council4/mtg/cards/tokens/o"
	"github.com/natefinch/council4/mtg/cards/tokens/p"
	"github.com/natefinch/council4/mtg/cards/tokens/r"
	"github.com/natefinch/council4/mtg/cards/tokens/s"
	"github.com/natefinch/council4/mtg/cards/tokens/t"
	"github.com/natefinch/council4/mtg/cards/tokens/u"
	"github.com/natefinch/council4/mtg/cards/tokens/v"
	"github.com/natefinch/council4/mtg/cards/tokens/w"
	"github.com/natefinch/council4/mtg/cards/tokens/z"
)

// Cards lists all generated playable token definitions.
var Cards = slices.Concat(
	a.Cards,
	b.Cards,
	c.Cards,
	d.Cards,
	e.Cards,
	f.Cards,
	g.Cards,
	h.Cards,
	i.Cards,
	k.Cards,
	l.Cards,
	m.Cards,
	n.Cards,
	o.Cards,
	p.Cards,
	r.Cards,
	s.Cards,
	t.Cards,
	u.Cards,
	v.Cards,
	w.Cards,
	z.Cards,
)
