// Code generated by genregistry; DO NOT EDIT.

package cards

import (
	"github.com/natefinch/council4/mtg/cards/a"
	"github.com/natefinch/council4/mtg/cards/b"
	"github.com/natefinch/council4/mtg/cards/c"
	"github.com/natefinch/council4/mtg/cards/cardset"
	"github.com/natefinch/council4/mtg/cards/d"
	"github.com/natefinch/council4/mtg/cards/e"
	"github.com/natefinch/council4/mtg/cards/f"
	"github.com/natefinch/council4/mtg/cards/g"
	"github.com/natefinch/council4/mtg/cards/h"
	"github.com/natefinch/council4/mtg/cards/i"
	"github.com/natefinch/council4/mtg/cards/j"
	"github.com/natefinch/council4/mtg/cards/k"
	"github.com/natefinch/council4/mtg/cards/l"
	"github.com/natefinch/council4/mtg/cards/m"
	"github.com/natefinch/council4/mtg/cards/n"
	"github.com/natefinch/council4/mtg/cards/o"
	"github.com/natefinch/council4/mtg/cards/p"
	"github.com/natefinch/council4/mtg/cards/q"
	"github.com/natefinch/council4/mtg/cards/r"
	"github.com/natefinch/council4/mtg/cards/s"
	"github.com/natefinch/council4/mtg/cards/t"
	"github.com/natefinch/council4/mtg/cards/u"
	"github.com/natefinch/council4/mtg/cards/v"
	"github.com/natefinch/council4/mtg/cards/w"
	"github.com/natefinch/council4/mtg/cards/x"
	"github.com/natefinch/council4/mtg/cards/y"
	"github.com/natefinch/council4/mtg/cards/z"
)

// defaultCardSets returns the Cards entries from every committed letter
// sub-package, in alphabetical order.
func defaultCardSets() [][]cardset.Entry {
	return [][]cardset.Entry{
		a.Cards,
		b.Cards,
		c.Cards,
		d.Cards,
		e.Cards,
		f.Cards,
		g.Cards,
		h.Cards,
		i.Cards,
		j.Cards,
		k.Cards,
		l.Cards,
		m.Cards,
		n.Cards,
		o.Cards,
		p.Cards,
		q.Cards,
		r.Cards,
		s.Cards,
		t.Cards,
		u.Cards,
		v.Cards,
		w.Cards,
		x.Cards,
		y.Cards,
		z.Cards,
	}
}
