// Code generated by genregistry; DO NOT EDIT.

package cards

import (
	"github.com/natefinch/council4/mtg/cards/a"
	"github.com/natefinch/council4/mtg/cards/b"
	"github.com/natefinch/council4/mtg/cards/c"
	"github.com/natefinch/council4/mtg/cards/d"
	"github.com/natefinch/council4/mtg/cards/e"
	"github.com/natefinch/council4/mtg/cards/f"
	"github.com/natefinch/council4/mtg/cards/g"
	"github.com/natefinch/council4/mtg/cards/h"
	"github.com/natefinch/council4/mtg/cards/i"
	"github.com/natefinch/council4/mtg/cards/k"
	"github.com/natefinch/council4/mtg/cards/l"
	"github.com/natefinch/council4/mtg/cards/m"
	"github.com/natefinch/council4/mtg/cards/n"
	"github.com/natefinch/council4/mtg/cards/p"
	"github.com/natefinch/council4/mtg/cards/r"
	"github.com/natefinch/council4/mtg/cards/s"
	"github.com/natefinch/council4/mtg/cards/t"
	"github.com/natefinch/council4/mtg/game"
)

// defaultCardSets returns the Cards slice from every committed letter
// sub-package, in alphabetical order.
func defaultCardSets() [][]*game.CardDef {
	return [][]*game.CardDef{
		a.Cards,
		b.Cards,
		c.Cards,
		d.Cards,
		e.Cards,
		f.Cards,
		g.Cards,
		h.Cards,
		i.Cards,
		k.Cards,
		l.Cards,
		m.Cards,
		n.Cards,
		p.Cards,
		r.Cards,
		s.Cards,
		t.Cards,
	}
}
