// Code generated by gencardlist; DO NOT EDIT.

package x

import "github.com/natefinch/council4/mtg/game"

// Cards lists all card definitions in this package.
var Cards = []*game.CardDef{
	X23DeadlyWeapon,
	XerexStrobeKnight,
	XiahouDunTheOneEyed,
	XunYuWeiAdvisor,
}
