// Code generated by gencardlist; DO NOT EDIT.

package e

import "github.com/natefinch/council4/mtg/game"

// Cards lists all card definitions in this package.
var Cards = []*game.CardDef{
	EbonyCharm,
	EclipsedBoggart,
	EclipsedElf,
	EclipsedFlamekin,
	EclipsedKithkin,
	EclipsedMerrow,
	EdgeOfTheDivinity,
	EerieInterlude,
	EfreetFlamepainter,
	EiganjoCastle,
	ElspethSSmite,
	ElvishFarmer,
	ElvishRejuvenator,
	EmberBeast,
	EmberIslandProduction,
	EmberethPaladin,
	EmberheartChallenger,
	EmberwildeCaliph,
	EmblemOfTheWarmind,
	EmeraldCharm,
	EmrakulSMessenger,
	EndlessWurm,
	EnduringCourage,
	EnterprisingScallywag,
	EpicConfrontation,
	EquestrianSkill,
	EsperBattlemage,
	EtherealChampion,
	ExaltedAngel,
	ExemplarOfStrength,
	EyeblightMassacre,
	EyeblightSEnding,
	EzrimAgencyChief,
}
