// Code generated by gencardlist; DO NOT EDIT.

package e

import "github.com/natefinch/council4/mtg/game"

// Cards lists all card definitions in this package.
var Cards = []*game.CardDef{
	EerieInterlude,
	EmblemOfTheWarmind,
	EnduringCourage,
	EpicConfrontation,
}
