package main

import (
	"cmp"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"slices"
	"strings"
)

// fingerprintLength is how many hex characters of each card's digest the
// manifest records. Eight bytes is far more than enough to make an accidental
// collision across a corpus of tens of thousands of cards impossible in
// practice, and it keeps the manifest narrow enough to read.
const fingerprintLength = 16

// fingerprint is one card's entry in the corpus manifest.
type fingerprint struct {
	Name   string
	Digest string
}

// writeFingerprints records a digest of every supported card's generated source
// in a committed manifest.
//
// This is the corpus-wide regression net. Nothing reads the file: its whole
// value is the diff. Because CI regenerates and commits the documentation set
// on every branch, a pull request that changes lowering shows, with no author
// effort, exactly which cards it changed and how many. A change that intends to
// support one new card and silently rewrites four hundred others cannot hide,
// and a refactor that claims to preserve behavior is proved by an empty diff.
//
// That visibility is what lets a card pull request stop shipping a defensive
// hand-written assertion for every card it might have disturbed.
//
// The digest covers the rendered Go source rather than the semantic IR, because
// the source is the artifact that actually ships. Reformatting the renderer
// therefore churns the whole manifest, which is correct: that change did touch
// every card, and its blast radius is worth seeing.
func writeFingerprints(path string, results []result) error {
	prints := make([]fingerprint, 0, len(results))
	for _, result := range results {
		if result.exclusion != "" || result.err != nil || len(result.diagnostics) > 0 {
			continue
		}
		sum := sha256.Sum256([]byte(result.source))
		prints = append(prints, fingerprint{
			Name:   result.card.Name,
			Digest: hex.EncodeToString(sum[:])[:fingerprintLength],
		})
	}
	// Sort by name the way the supported list does, so the two files can be
	// read side by side, then by digest so duplicate printings of one name
	// keep a stable order across runs.
	slices.SortFunc(prints, func(a, b fingerprint) int {
		if compared := cmp.Compare(strings.ToLower(a.Name), strings.ToLower(b.Name)); compared != 0 {
			return compared
		}
		if compared := cmp.Compare(a.Name, b.Name); compared != 0 {
			return compared
		}
		return cmp.Compare(a.Digest, b.Digest)
	})

	var builder strings.Builder
	_, _ = builder.WriteString("# Corpus fingerprints\n")
	_, _ = builder.WriteString("#\n")
	_, _ = builder.WriteString("# One line per supported card: a digest of its generated Go source, then\n")
	_, _ = builder.WriteString("# its name. Regenerated by `mage supportDocs`; nothing reads it.\n")
	_, _ = builder.WriteString("#\n")
	_, _ = builder.WriteString("# The diff is the point: it shows which cards a change actually altered.\n")
	_, _ = builder.WriteString("# An empty diff proves a refactor preserved behavior corpus-wide.\n")
	_, _ = fmt.Fprintf(&builder, "#\n# %d supported cards\n\n", len(prints))
	for _, print := range prints {
		_, _ = fmt.Fprintf(&builder, "%s  %s\n", print.Digest, print.Name)
	}
	return writeDocumentationFile(path, builder.String())
}
