// Code generated by gencardlist; DO NOT EDIT.

package g

import "github.com/natefinch/council4/mtg/game"

// Cards lists all card definitions in this package.
var Cards = []*game.CardDef{
	GarenbrigPaladin,
	GarrukPrimalHunter,
	GarrulousSycophant,
	GavonyIronwright,
	GempalmAvenger,
	GempalmStrider,
	GeralfSMindcrusher,
	GhostHounds,
	Ghostway,
	GiantSGrasp,
	GiftOfTheGargantuan,
	GigglingSkitterspike,
	GimliCounterOfKills,
	GimliSRecklessMight,
	GlaringFleshraker,
	GlimpseTheUnthinkable,
	GlintNestCrane,
	Gloomwidow,
	GoblinDarkDwellers,
	GoblinLookout,
	GoblinPyromancer,
	GolgariRaiders,
	GracefulRestoration,
	GraveVenerations,
	GravenCairns,
	Gravepurge,
	GreaterTanuki,
	GreenwheelLiberator,
	Groundskeeper,
	GrowthCycle,
	GuardianProject,
	GuruPathik,
	GwaihirGreatestOfTheEagles,
}
