// Code generated by gencardlist; DO NOT EDIT.

package g

import "github.com/natefinch/council4/mtg/game"

// Cards lists all card definitions in this package.
var Cards = []*game.CardDef{
	GiantSGrasp,
	GigglingSkitterspike,
	GimliCounterOfKills,
	GimliSRecklessMight,
	GravenCairns,
	GreaterTanuki,
	GreenwheelLiberator,
	GrowthCycle,
	GuardianProject,
}
