// Code generated by gencardlist; DO NOT EDIT.

package w

import "github.com/natefinch/council4/mtg/game"

// Cards lists all card definitions in this package.
var Cards = []*game.CardDef{
	WalkThePlank,
	WallOfEssence,
	WallOfHope,
	WallOfJunk,
	WanderingMind,
	WanderlightSpirit,
	WantedGriffin,
	WarDance,
	WardSliver,
	WarriorAngel,
	Weatherlight,
	WebOfLifeAndDestiny,
	WelkinTern,
	WhiskerquillScribe,
	WhiteWard,
	Wight,
	WildInstincts,
	WildestDreams,
	WillOfTheTemur,
	WindbriskHeights,
	Windscouter,
	WingspanMentor,
	WitchSMist,
	Withstand,
	WizardReplica,
	WojekBodyguard,
	WoodenSphere,
	WoodlandWanderer,
	WorldBreaker,
	WrithingChrysalis,
}
