// Code generated by gencardlist; DO NOT EDIT.

package p

import "github.com/natefinch/council4/mtg/game"

// Cards lists all card definitions in this package.
var Cards = []*game.CardDef{
	PalliationAccord,
	PallidMycoderm,
	ParadoxSurveyor,
	PathOfAnnihilation,
	PatronWizard,
	PeerThroughDepths,
	PentarchWard,
	PerfectIntimidation,
	PetrifyingMeddler,
	PestilentCauldron,
	PhalanxTactics,
	PhantomWhelp,
	PhyrexianDriver,
	PicturesOfSpiderMan,
	PillagingHorde,
	PlanarGuide,
	PlantElemental,
	PointTheWay,
	PotionerSTrove,
	PredatorOoze,
	PricklyPair,
	PrimalMight,
	PrimevalForce,
	PrismariCharm,
	PrismaticUndercurrents,
	PrizedStatue,
	PropagatorDrone,
	ProsperityTycoon,
	PsychicVenom,
	PsychotropeThallid,
	PublicThoroughfare,
	PuncturingBlow,
	PurgingStormbrood,
	PutridImp,
}
