// Code generated by gencardlist; DO NOT EDIT.

package p

import "github.com/natefinch/council4/mtg/game"

// Cards lists all card definitions in this package.
var Cards = []*game.CardDef{
	PathOfAnnihilation,
	PlanarGuide,
	PricklyPair,
	PrimalMight,
	PrizedStatue,
	PropagatorDrone,
	ProsperityTycoon,
	PsychicVenom,
	PuncturingBlow,
}
