// Code generated by gencardlist; DO NOT EDIT.

package r

import "github.com/natefinch/council4/mtg/game"

// Cards lists all card definitions in this package.
var Cards = []*game.CardDef{
	RakishCrew,
	RampantGrowth,
	RancorousArchaic,
	ReduceToAshes,
	RenegadeRallier,
	RhinoSRampage,
	RhonasTheIndomitable,
	Riddlekeeper,
	RiseFromTheTides,
	RiteOfFlame,
	RiteOfOblivion,
	RotcrownGhoul,
	RuthlessPredation,
}
