// Code generated by gencardlist; DO NOT EDIT.

package r

import "github.com/natefinch/council4/mtg/game"

// Cards lists all card definitions in this package.
var Cards = []*game.CardDef{
	RakishCrew,
	RampantGrowth,
	RancorousArchaic,
	RealmCloakedGiant,
	ReaperFromTheAbyss,
	ReduceToAshes,
	RendFlesh,
	RenegadeRallier,
	RestorationAngel,
	ReturnToTheRanks,
	Reveillark,
	RhinoSRampage,
	RhonasTheIndomitable,
	Riddlekeeper,
	RiseFromTheTides,
	RiteOfFlame,
	RiteOfOblivion,
	RiteOfReplication,
	RiveteersOverlook,
	RoamingGhostlight,
	RosethornHalberd,
	RotcrownGhoul,
	RuthlessPredation,
}
