// Code generated by gencardlist; DO NOT EDIT.

package j

import "github.com/natefinch/council4/mtg/game"

// Cards lists all card definitions in this package.
var Cards = []*game.CardDef{
	JaceBeleren,
	JaceSPhantasm,
	JaceSSentinel,
	JackalFamiliar,
	JadeLeech,
	JhessianBalmgiver,
	JidoorAristocraticCapital,
	JinxedIdol,
	JinxedRing,
	JirinaDauntlessGeneral,
	JoinTheDead,
	JoragaWarcaller,
	JudgeSFamiliar,
	JungleBasin,
	JunkGolem,
}
