// Code generated by gencardlist; DO NOT EDIT.

package l

import "github.com/natefinch/council4/mtg/game"

// Cards lists all card definitions in this package.
var Cards = []*game.CardDef{
	LassoedByTheLaw,
	LatticeBladeMantis,
	LavaCoil,
	LeadBellyChimera,
	LeadTheStampede,
	LegolasMasterArcher,
	LifeBurst,
	LifecraftCavalry,
	Lifesmith,
	LightningBolt,
	LightningSerpent,
	LilianaSSpoils,
	LivingPhone,
	LlanowarWastes,
	LocthwainPaladin,
	LongRoadHome,
	LordDreggInsectInvader,
	LoxodonWarhammer,
	LupinflowerVillage,
	LustForWar,
}
