// Code generated by gencardlist; DO NOT EDIT.

package z

import "github.com/natefinch/council4/mtg/game"

// Cards lists all card definitions in this package.
var Cards = []*game.CardDef{
	ZadaSCommando,
	ZhangHeWeiGeneral,
	ZulaportChainmage,
}
