// Code generated by gencardlist; DO NOT EDIT.

package k

import "github.com/natefinch/council4/mtg/game"

// Cards lists all card definitions in this package.
var Cards = []*game.CardDef{
	KaaliaZenithSeeker,
	KalastriaHighborn,
	KamahlFistOfKrosa,
	KamahlHeartOfKrosa,
	KamiOfTheHonoredDead,
	Kapow,
	KarplusanForest,
	KashiTribeReaver,
	KashiTribeWarriors,
	KavuAggressor,
	KavuPrimarch,
	KayaSGhostform,
	KederektLeviathan,
	KeensightMentor,
	KeiTakahashi,
	KessigCagebreakers,
	KessigWolfRun,
	KhalniAmbush,
	KhalniHeartExpedition,
	KinTreeInvocation,
	KitesailApprentice,
	KineticAugur,
	KithkinHealer,
	KjeldoranGargoyle,
	KodamaOfTheSouthTree,
	KolaghanAspirant,
	KolaghanWarmonger,
	KorDuelist,
	KoskunFalls,
	KrosanDrover,
	KrotiqNestguard,
	KusariGama,
	KyoshiIslandPlaza,
	KyoshiWarriorExemplars,
}
