// Code generated by gencardlist; DO NOT EDIT.

package k

import "github.com/natefinch/council4/mtg/game"

// Cards lists all card definitions in this package.
var Cards = []*game.CardDef{
	KaaliaZenithSeeker,
	Kapow,
	KarplusanForest,
	KayaSGhostform,
	KeensightMentor,
	KessigCagebreakers,
	KessigWolfRun,
	KhalniAmbush,
	KodamaOfTheSouthTree,
	KolaghanWarmonger,
	KrosanDrover,
	KusariGama,
}
