// Code generated by gencardlist; DO NOT EDIT.

package k

import "github.com/natefinch/council4/mtg/game"

// Cards lists all card definitions in this package.
var Cards = []*game.CardDef{
	KaaliaZenithSeeker,
	KamiOfTheHonoredDead,
	Kapow,
	KarplusanForest,
	KayaSGhostform,
	KeensightMentor,
	KeiTakahashi,
	KessigCagebreakers,
	KessigWolfRun,
	KhalniAmbush,
	KhalniHeartExpedition,
	KithkinHealer,
	KjeldoranGargoyle,
	KodamaOfTheSouthTree,
	KolaghanAspirant,
	KolaghanWarmonger,
	KoskunFalls,
	KrosanDrover,
	KusariGama,
	KyoshiIslandPlaza,
}
