// Code generated by compilecards; DO NOT EDIT.

package n

import "github.com/natefinch/council4/mtg/game"

// Cards lists all card definitions in this package.
var Cards = []*game.CardDef{
	NecronWarriorToken4578c6380438457db1678d7667ecdedd,
	NightmareHorrorTokeneabcfcf54f5142c18eb838810d6ebd47,
	NinjaToken2589ab298c244e8e80a6b697df27d350,
	NinjaToken640ee47bed18424b9e04e03ec031ba66,
	NinjaTokene91f412a662644fca735a2cce5225622,
	NinjaTurtleSpiritTokena05785890c684024943d42066dad4ff3,
}
