package main

import (
	"fmt"
	"go/format"
	"slices"
	"strings"
)

// renderLiterals emits the generated constant-name tables for every enum type.
func renderLiterals(enums []enumType) ([]byte, error) {
	var b strings.Builder
	_, _ = b.WriteString("// Code generated by cardgen/cmd/genrender. DO NOT EDIT.\n\n")
	_, _ = b.WriteString("package cardgen\n\n")
	writeImports(&b, enums)
	if err := writeTables(&b, enums); err != nil {
		return nil, err
	}
	src, err := format.Source([]byte(b.String()))
	if err != nil {
		return nil, fmt.Errorf("formatting generated source: %w", err)
	}
	return src, nil
}

func writeImports(b *strings.Builder, enums []enumType) {
	paths := make([]string, 0, len(enums))
	for _, e := range enums {
		if !slices.Contains(paths, e.Pkg.Path()) {
			paths = append(paths, e.Pkg.Path())
		}
	}
	slices.Sort(paths)
	_, _ = b.WriteString("import (\n")
	for _, p := range paths {
		_, _ = fmt.Fprintf(b, "\t%q\n", p)
	}
	_, _ = b.WriteString(")\n\n")
}

func writeTables(b *strings.Builder, enums []enumType) error {
	for _, e := range enums {
		if isBitmask(e) {
			if err := writeFlags(b, e); err != nil {
				return err
			}
			continue
		}
		_, _ = fmt.Fprintf(b, "// %s maps each exported %s constant to the Go\n", e.TableName(), e.Ref())
		_, _ = b.WriteString("// expression that names it in generated card source.\n")
		_, _ = fmt.Fprintf(b, "var %s = map[%s]string{\n", e.TableName(), e.Ref())
		for _, v := range e.Values {
			ref := v.Ref(e.Pkg)
			_, _ = fmt.Fprintf(b, "\t%s: %q,%s\n", ref, ref, v.comment())
		}
		_, _ = b.WriteString("}\n\n")
	}
	return nil
}

// writeFlags emits a bitmask type's flags in ascending value order, as pairs of
// flag and the Go expression naming it.
func writeFlags(b *strings.Builder, e enumType) error {
	values, err := flags(e)
	if err != nil {
		return err
	}
	_, _ = fmt.Fprintf(b, "// %s lists every exported %s flag in ascending\n", e.FlagsName(), e.Ref())
	_, _ = b.WriteString("// value order, which is the order set flags are ORed together in generated\n")
	_, _ = b.WriteString("// card source.\n")
	_, _ = fmt.Fprintf(b, "var %s = []enumFlag[%s]{\n", e.FlagsName(), e.Ref())
	for _, v := range values {
		ref := v.Ref(e.Pkg)
		_, _ = fmt.Fprintf(b, "\t{Flag: %s, Literal: %q},\n", ref, ref)
	}
	_, _ = b.WriteString("}\n\n")
	return nil
}
