package main

import (
	"bytes"
	"fmt"
	"go/format"
	"slices"
	"strings"
)

// renderStructs returns the formatted contents of the generated struct renderer
// file: a renderer for every reachable struct, a zero predicate for every struct
// Go cannot compare with ==, and a dispatch for every reachable interface.
func renderStructs(graph *reachable) ([]byte, error) {
	if err := checkOpaqueRenderers(graph); err != nil {
		return nil, err
	}
	e := newEmitter(graph)
	targets := generationTargets(graph)

	var b strings.Builder
	for _, named := range nonComparableTargets(graph, targets) {
		if err := e.emitZeroFunc(&b, named); err != nil {
			return nil, err
		}
	}
	for _, iface := range graph.Interfaces {
		if err := e.emitDispatch(&b, iface, graph.Implementations[qualified(iface)]); err != nil {
			return nil, err
		}
	}
	for _, named := range targets {
		if err := e.emitStructRenderer(&b, named); err != nil {
			return nil, err
		}
	}

	var head strings.Builder
	_, _ = head.WriteString("// Code generated by cardgen/cmd/genrender. DO NOT EDIT.\n\n")
	_, _ = head.WriteString("package cardgen\n\n")
	writeStructImports(&head, e.used)

	src, err := format.Source([]byte(head.String() + b.String()))
	if err != nil {
		return nil, fmt.Errorf("formatting generated structs: %w\n%s", err, numbered(head.String()+b.String()))
	}
	return src, nil
}

// writeStructImports emits the import block for exactly the packages the
// emitted source names.
func writeStructImports(b *strings.Builder, pkgs map[string]string) {
	_, _ = b.WriteString("import (\n")
	_, _ = b.WriteString("\t\"errors\"\n\t\"fmt\"\n\t\"strconv\"\n\t\"strings\"\n\n")
	for _, name := range sortedStringKeys(pkgs) {
		_, _ = fmt.Fprintf(b, "\t%q\n", pkgs[name])
	}
	_, _ = b.WriteString(")\n")
}

func sortedStringKeys(m map[string]string) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	slices.Sort(out)
	return out
}

// numbered prefixes each line with its number, so a formatting failure in
// generated source can be located.
func numbered(src string) string {
	var b bytes.Buffer
	for i, line := range strings.Split(src, "\n") {
		_, _ = fmt.Fprintf(&b, "%5d: %s\n", i+1, line)
	}
	return b.String()
}
