// Code generated by gencardlist; DO NOT EDIT.

package d

import "github.com/natefinch/council4/mtg/game"

// Cards lists all card definitions in this package.
var Cards = []*game.CardDef{
	DaringWaverider,
	DauthiMindripper,
	DeadeyeHarpooner,
	DeathDenied,
	DeathcapGlade,
	Decommission,
	DemonicAppetite,
	DescentOfTheDragons,
	DesertSDue,
	DingusEgg,
	DingusStaff,
	DirectorNickFury,
	DivineVisitation,
	DomriAnarchOfBolas,
	DonatelloMutantMechanic,
	DragonEgg,
	DragonskullSummit,
	DranaSChosen,
	DuskfangMentor,
}
