// Code generated by gencardlist; DO NOT EDIT.

package d

import "github.com/natefinch/council4/mtg/game"

// Cards lists all card definitions in this package.
var Cards = []*game.CardDef{
	DAvenantHealer,
	DaringWaverider,
	DaruHealer,
	DauthiMindripper,
	Dawnfluke,
	DeadeyeHarpooner,
	DeathDenied,
	DeathcapGlade,
	DeathsporeThallid,
	Decommission,
	Decompose,
	DeepGoblinSkulltaker,
	DemonicAppetite,
	DescentOfTheDragons,
	DesertSDue,
	DingusEgg,
	DingusStaff,
	DirectorNickFury,
	DisruptivePitmage,
	DisruptiveStudent,
	DiversionUnit,
	DirtyWererat,
	DivineVisitation,
	DocSamsonSuperPsychiatrist,
	DomriAnarchOfBolas,
	DonatelloMutantMechanic,
	DragonEgg,
	DragonSHoard,
	DragonskullSummit,
	DrakeHatcher,
	DranaSChosen,
	DuchessWaywardTavernkeep,
	DreamcallerSiren,
	DuskfangMentor,
	DesolationTwin,
}
