// Code generated by gencardlist; DO NOT EDIT.

package i

import "github.com/natefinch/council4/mtg/game"

// Cards lists all card definitions in this package.
var Cards = []*game.CardDef{
	IcewindStalwart,
	IchorWellspring,
	IconOfAncestry,
	IgnobleHierarch,
	ImpendingDoom,
	InameLifeAspect,
	IncreasingDevotion,
	Incubation,
	InfernoFist,
	InfiltrationLens,
	IngeniousProdigy,
	IngeniousSmith,
	InnerDemon,
	InsectoidExterminator,
	Insolence,
	InvasionOfIxalan,
	IroasSBlessing,
	IronHeartChimera,
	ItThatHeraldsTheEnd,
}
