// Code generated by gencardlist; DO NOT EDIT.

package i

import "github.com/natefinch/council4/mtg/game"

// Cards lists all card definitions in this package.
var Cards = []*game.CardDef{
	IchorWellspring,
	IgnobleHierarch,
	ImpendingDoom,
	InameLifeAspect,
	IncreasingDevotion,
	InfernoFist,
	InfiltrationLens,
	IngeniousProdigy,
	InnerDemon,
	InsectoidExterminator,
	Insolence,
	IroasSBlessing,
	IronHeartChimera,
	ItThatHeraldsTheEnd,
}
