// Code generated by compilecards; DO NOT EDIT.

package j

import "github.com/natefinch/council4/mtg/game"

// Cards lists all card definitions in this package.
var Cards = []*game.CardDef{
	JunkToken7034bca48ba047a6886eecbd829ddaec,
}
