// Command genregistry scans the mtg/cards directory for letter card
// sub-packages (single-letter package directories such as a/, b/, ...) and
// generates registry_sets.go, which aggregates their exported Cards slices for
// cards.NewDefaultRegistry.
//
// Usage (typically via go generate from the mtg/cards directory):
//
//	go run github.com/natefinch/council4/cardgen/cmd/genregistry
//
// Token definitions (the tokens/ sub-package) are intentionally excluded: they
// are not real cards and must not resolve from a decklist.
package main

import (
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"slices"
	"strings"
)

const (
	cardsetPkgPath = "github.com/natefinch/council4/mtg/cards/cardset"
	cardsPkgPath   = "github.com/natefinch/council4/mtg/cards"
)

func main() {
	if err := run(); err != nil {
		_, _ = fmt.Fprintf(os.Stderr, "genregistry: %v\n", err)
		os.Exit(1)
	}
}

func run() error {
	dir, err := os.Getwd()
	if err != nil {
		return err
	}
	letters, err := letterPackages(dir)
	if err != nil {
		return err
	}
	src, err := render(letters)
	if err != nil {
		return err
	}
	outPath := filepath.Join(dir, "registry_sets.go")
	if err := os.WriteFile(outPath, src, 0o600); err != nil {
		return fmt.Errorf("writing %s: %w", outPath, err)
	}
	_, _ = fmt.Fprintf(os.Stderr, "Generated %s with %d letter packages\n", outPath, len(letters))
	return nil
}

// letterPackages returns the names of single-letter card sub-package
// directories under dir, sorted alphabetically.
func letterPackages(dir string) ([]string, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, err
	}
	var letters []string
	for _, entry := range entries {
		name := entry.Name()
		if entry.IsDir() && len(name) == 1 && name[0] >= 'a' && name[0] <= 'z' {
			letters = append(letters, name)
		}
	}
	slices.Sort(letters)
	return letters, nil
}

// render builds the gofmt-formatted source for registry_sets.go.
func render(letters []string) ([]byte, error) {
	var b strings.Builder
	_, _ = b.WriteString("// Code generated by genregistry; DO NOT EDIT.\n\n")
	_, _ = b.WriteString("package cards\n\n")
	_, _ = b.WriteString("import (\n")
	_, _ = fmt.Fprintf(&b, "\t%q\n", cardsetPkgPath)
	for _, letter := range letters {
		_, _ = fmt.Fprintf(&b, "\t%q\n", cardsPkgPath+"/"+letter)
	}
	_, _ = b.WriteString(")\n\n")
	_, _ = b.WriteString("// defaultCardSets returns the Cards entries from every committed letter\n")
	_, _ = b.WriteString("// sub-package, in alphabetical order.\n")
	_, _ = b.WriteString("func defaultCardSets() [][]cardset.Entry {\n")
	_, _ = b.WriteString("\treturn [][]cardset.Entry{\n")
	for _, letter := range letters {
		_, _ = fmt.Fprintf(&b, "\t\t%s.Cards,\n", letter)
	}
	_, _ = b.WriteString("\t}\n")
	_, _ = b.WriteString("}\n")
	return format.Source([]byte(b.String()))
}
