// Code generated by compilecards; DO NOT EDIT.

package u

import "github.com/natefinch/council4/mtg/game"

// Cards lists all card definitions in this package.
var Cards = []*game.CardDef{
	UltramarinesHonourGuardToken00bc99d92cc44dd5a37b4918fff8160a,
	UnwaveringInitiateToken92837e49ebc24a0586fdcf014314e1e0,
	UrzanAutomatonToken8bf396aed9ac4711af60d97f439ab76c,
}
