// Code generated by gencardlist; DO NOT EDIT.

package n

import "github.com/natefinch/council4/mtg/game"

// Cards lists all card definitions in this package.
var Cards = []*game.CardDef{
	NacreTalisman,
	NarnamRenegade,
	NarsetParterOfVeils,
	NarsetSRebuke,
	NatureSLore,
	NecraDisciple,
	NecroticWound,
	NemataGroveGuardian,
	NemesisOfReason,
	NeonateSRush,
	NessianWanderer,
	NettleGuard,
	NeyithOfTheDireHunt,
	NezumiLinkbreaker,
	NibelheimAflame,
	NickValentinePrivateEye,
	NightMarketAeronaut,
	NightwhorlHermit,
	NimblewrightSchematic,
	NivixCyclops,
	NoblePurpose,
	NobleVestige,
	NoggleBandit,
	NoxiousGhoul,
	NoxiousHatchling,
	Nulldrifter,
	NumotTheDevastator,
	NyxbloomAncient,
}
