// Code generated by gencardlist; DO NOT EDIT.

package f

import "github.com/natefinch/council4/mtg/game"

// Cards lists all card definitions in this package.
var Cards = []*game.CardDef{
	FactOrFiction,
	FaerieMechanist,
	FaithUnbroken,
	FalseMemories,
	FanaticOfRhonas,
	FaramirStewardOfGondor,
	FarhavenElf,
	Farseek,
	FeedTheFlames,
	FeralThallid,
	Fiendlash,
	FightAsOne,
	FireLitThicket,
	FireWhip,
	FiresOfYavimaya,
	FiveAlarmFire,
	FlameBlessedBolt,
	FlamespeakerSWill,
	FlintGolem,
	FloriferousVinewall,
	FootMystic,
	FootbottomFeast,
	Forest,
	ForeverYoung,
	ForgingTheAnchor,
	FormAPosse,
	FracturedSanity,
	FranticSalvage,
	FrillscareMentor,
	FrontierSeeker,
	FungalBloom,
}
