// Code generated by gencardlist; DO NOT EDIT.

package f

import "github.com/natefinch/council4/mtg/game"

// Cards lists all card definitions in this package.
var Cards = []*game.CardDef{
	FaithUnbroken,
	FanaticOfRhonas,
	FarhavenElf,
	Farseek,
	Fiendlash,
	FireLitThicket,
	FireWhip,
	FiresOfYavimaya,
	FlamespeakerSWill,
	FootMystic,
	Forest,
}
