// Code generated by gencardlist; DO NOT EDIT.

package h

import "github.com/natefinch/council4/mtg/game"

// Cards lists all card definitions in this package.
var Cards = []*game.CardDef{
	HalanaAndAlenaPartners,
	HallowedHealer,
	HaraldKingOfSkemfar,
	HarmonicProdigy,
	HarmoniousArchon,
	HarperRecruiter,
	HarvestHand,
	HarvestSeason,
	HauntedRidge,
	HazoretGodseeker,
	Heal,
	HealingLeaves,
	HealingSalve,
	HeartfireHero,
	HeartsOnFire,
	HeatOfBattle,
	Hecatomb,
	HeirloomAuntie,
	HellionCrucible,
	Hellrider,
	HelmOfAwakening,
	HengeWalker,
	HerdMigration,
	HeronBlessedGeist,
	HiddenFootblade,
	HiddenHorror,
	HiddenStockpile,
	HoldAtBay,
	HoofprintsOfTheStag,
	HopeAgainstHope,
	HornbashMentor,
	HornedCheetah,
	HotSprings,
	HoverguardObserver,
	HowlOfTheNightPack,
	HuatliRadiantChampion,
	HuntTheHunter,
	HuntTheWeak,
	HunterSTalent,
	Hypochondria,
}
