// Code generated by gencardlist; DO NOT EDIT.

package h

import "github.com/natefinch/council4/mtg/game"

// Cards lists all card definitions in this package.
var Cards = []*game.CardDef{
	HalanaAndAlenaPartners,
	HarmonicProdigy,
	HauntedRidge,
	HazoretGodseeker,
	HeatOfBattle,
	HiddenStockpile,
	HuntTheHunter,
	HuntTheWeak,
	HunterSTalent,
}
