// Code generated by gencardlist; DO NOT EDIT.

package v

import "github.com/natefinch/council4/mtg/game"

// Cards lists all card definitions in this package.
var Cards = []*game.CardDef{
	VantressPaladin,
	VaporSnare,
	Vaporkin,
	VastlandsScavenger,
	Vebulid,
	VengefulRebel,
	Vesperlark,
	VictorTimelyWilyTycoon,
	VitasporeThallid,
	VivienReid,
	VoiceOfAll,
	VoraciousHatchling,
	VulshokWarBoar,
}
