// Code generated by gencardlist; DO NOT EDIT.

package v

import "github.com/natefinch/council4/mtg/game"

// Cards lists all card definitions in this package.
var Cards = []*game.CardDef{
	VampireHexmage,
	VampiricDragon,
	VampiricLink,
	VantressPaladin,
	VaporSnare,
	Vaporkin,
	VastlandsScavenger,
	Vebulid,
	VengefulRebel,
	Vesperlark,
	VeteranGuardmouse,
	VictorTimelyWilyTycoon,
	VitasporeThallid,
	VivienReid,
	VodalianHexcatcher,
	VodalianMage,
	VoiceOfAll,
	VoraciousHatchling,
	VortexRunner,
	VraskaSFinisher,
	VrynWingmare,
	VulshokWarBoar,
}
