// Command gencardlist scans a card sub-package directory for exported CardDef
// variables and generates a cards.go file listing them all.
//
// Usage (typically via go generate):
//
//	go run github.com/natefinch/council4/cardgen/cmd/gencardlist
//
// Run from the letter sub-package directory (e.g., mtg/cards/l/).
package main

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"slices"
	"strings"
	"unicode"
)

func main() {
	dir, err := os.Getwd()
	if err != nil {
		_, _ = fmt.Fprintf(os.Stderr, "error: %v\n", err)
		os.Exit(1)
	}

	pkgName := filepath.Base(dir)

	fset := token.NewFileSet()
	files, err := parsePackageFiles(fset, dir)
	if err != nil {
		_, _ = fmt.Fprintf(os.Stderr, "error parsing directory: %v\n", err)
		os.Exit(1)
	}

	var varNames []string
	for _, file := range files {
		for _, decl := range file.Decls {
			genDecl, ok := decl.(*ast.GenDecl)
			if !ok || genDecl.Tok != token.VAR {
				continue
			}
			for _, spec := range genDecl.Specs {
				vs, ok := spec.(*ast.ValueSpec)
				if !ok {
					continue
				}
				if !isCardDefVar(vs) {
					continue
				}
				for _, name := range vs.Names {
					if unicode.IsUpper(rune(name.Name[0])) {
						varNames = append(varNames, name.Name)
					}
				}
			}
		}
	}

	slices.Sort(varNames)

	var b strings.Builder
	_, _ = b.WriteString("// Code generated by gencardlist; DO NOT EDIT.\n\n")
	_, _ = fmt.Fprintf(&b, "package %s\n\n", pkgName)
	_, _ = b.WriteString("import \"github.com/natefinch/council4/mtg/game\"\n\n")
	_, _ = b.WriteString("// Cards lists all card definitions in this package.\n")
	_, _ = b.WriteString("var Cards = []*game.CardDef{\n")
	for _, name := range varNames {
		_, _ = fmt.Fprintf(&b, "\t%s,\n", name)
	}
	_, _ = b.WriteString("}\n")

	outPath := filepath.Join(dir, "cards.go")
	if err := os.WriteFile(outPath, []byte(b.String()), 0o600); err != nil {
		_, _ = fmt.Fprintf(os.Stderr, "error writing %s: %v\n", outPath, err)
		os.Exit(1)
	}

	_, _ = fmt.Fprintf(os.Stderr, "Generated %s with %d cards\n", outPath, len(varNames))
}

func parsePackageFiles(fset *token.FileSet, dir string) ([]*ast.File, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, err
	}
	files := make([]*ast.File, 0, len(entries))
	for _, entry := range entries {
		name := entry.Name()
		if entry.IsDir() || name == "cards.go" || strings.HasSuffix(name, "_test.go") || !strings.HasSuffix(name, ".go") {
			continue
		}
		file, err := parser.ParseFile(fset, filepath.Join(dir, name), nil, 0)
		if err != nil {
			return nil, err
		}
		files = append(files, file)
	}
	return files, nil
}

// isCardDefVar checks whether a var declaration is initialized with &game.CardDef{...}.
func isCardDefVar(vs *ast.ValueSpec) bool {
	if len(vs.Values) == 0 {
		return false
	}
	// Look for &game.CardDef{...} pattern in the initializer.
	for _, val := range vs.Values {
		unary, ok := val.(*ast.UnaryExpr)
		if !ok {
			continue
		}
		comp, ok := unary.X.(*ast.CompositeLit)
		if !ok {
			continue
		}
		sel, ok := comp.Type.(*ast.SelectorExpr)
		if !ok {
			continue
		}
		pkg, ok := sel.X.(*ast.Ident)
		if !ok {
			continue
		}
		if pkg.Name == "game" && sel.Sel.Name == "CardDef" {
			return true
		}
	}
	return false
}
