// Code generated by gencardlist; DO NOT EDIT.

package t

import "github.com/natefinch/council4/mtg/game"

// Cards lists all card definitions in this package.
var Cards = []*game.CardDef{
	TabletOfEpityr,
	TajuruStalwart,
	TapestryOfTheAges,
	TappingAtTheWindow,
	TatteredHaunter,
	TarrianSSoulcleaver,
	TeferiSProtection,
	TempestTechnique,
	TestOfFaith,
	Thallid,
	ThallidDevourer,
	ThallidGerminator,
	ThallidShellDweller,
	TheDawningArchaic,
	TheGitrogMonster,
	TheHauntOfHightower,
	TheIrencrag,
	ThingFromTheDeep,
	ThornThallid,
	ThoughtGorger,
	ThrabenDoomsayer,
	ThroneOfBone,
	ThroneWarden,
	ThunderingWurm,
	TinWingChimera,
	TolarianSerpent,
	TomeScour,
	TorrentialGearhulk,
	TowerOfMurmurs,
	ToweringWaveMystic,
	TranquilDomain,
	TransguildPromenade,
	TreasureHunt,
	TreefolkHealer,
	TroubledHealer,
	TwinflameTravelers,
}
