// Code generated by gencardlist; DO NOT EDIT.

package t

import "github.com/natefinch/council4/mtg/game"

// Cards lists all card definitions in this package.
var Cards = []*game.CardDef{
	TajuruStalwart,
	TapestryOfTheAges,
	TappingAtTheWindow,
	TeferiSProtection,
	TempestTechnique,
	TheDawningArchaic,
	TheHauntOfHightower,
	TheIrencrag,
	ThrabenDoomsayer,
	ThroneWarden,
	TinWingChimera,
	TolarianSerpent,
	TomeScour,
	TorrentialGearhulk,
	TowerOfMurmurs,
	ToweringWaveMystic,
	TranquilDomain,
	TreasureHunt,
	TwinflameTravelers,
}
