// Command gencardlist scans a card sub-package directory for exported CardDef
// variables and generates a cards.go file listing them all.
//
// Usage (typically via go generate):
//
//	go run ../../gencardlist/main.go
//
// Run from the letter sub-package directory (e.g., mtg/cards/l/).
package main

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"unicode"
)

func main() {
	dir, err := os.Getwd()
	if err != nil {
		fmt.Fprintf(os.Stderr, "error: %v\n", err)
		os.Exit(1)
	}

	pkgName := filepath.Base(dir)

	fset := token.NewFileSet()
	pkgs, err := parser.ParseDir(fset, dir, func(fi os.FileInfo) bool {
		// Skip the generated file itself and test files.
		return fi.Name() != "cards.go" && !strings.HasSuffix(fi.Name(), "_test.go")
	}, 0)
	if err != nil {
		fmt.Fprintf(os.Stderr, "error parsing directory: %v\n", err)
		os.Exit(1)
	}

	var varNames []string
	for _, pkg := range pkgs {
		for _, file := range pkg.Files {
			for _, decl := range file.Decls {
				genDecl, ok := decl.(*ast.GenDecl)
				if !ok || genDecl.Tok != token.VAR {
					continue
				}
				for _, spec := range genDecl.Specs {
					vs, ok := spec.(*ast.ValueSpec)
					if !ok {
						continue
					}
					if !isCardDefVar(vs) {
						continue
					}
					for _, name := range vs.Names {
						if unicode.IsUpper(rune(name.Name[0])) {
							varNames = append(varNames, name.Name)
						}
					}
				}
			}
		}
	}

	sort.Strings(varNames)

	var b strings.Builder
	b.WriteString("// Code generated by gencardlist; DO NOT EDIT.\n\n")
	b.WriteString(fmt.Sprintf("package %s\n\n", pkgName))
	b.WriteString("import \"github.com/natefinch/council4/mtg/game\"\n\n")
	b.WriteString("// Cards lists all card definitions in this package.\n")
	b.WriteString("var Cards = []*game.CardDef{\n")
	for _, name := range varNames {
		b.WriteString(fmt.Sprintf("\t%s,\n", name))
	}
	b.WriteString("}\n")

	outPath := filepath.Join(dir, "cards.go")
	if err := os.WriteFile(outPath, []byte(b.String()), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "error writing %s: %v\n", outPath, err)
		os.Exit(1)
	}

	fmt.Fprintf(os.Stderr, "Generated %s with %d cards\n", outPath, len(varNames))
}

// isCardDefVar checks whether a var declaration is initialized with &game.CardDef{...}.
func isCardDefVar(vs *ast.ValueSpec) bool {
	if len(vs.Values) == 0 {
		return false
	}
	// Look for &game.CardDef{...} pattern in the initializer.
	for _, val := range vs.Values {
		unary, ok := val.(*ast.UnaryExpr)
		if !ok {
			continue
		}
		comp, ok := unary.X.(*ast.CompositeLit)
		if !ok {
			continue
		}
		sel, ok := comp.Type.(*ast.SelectorExpr)
		if !ok {
			continue
		}
		pkg, ok := sel.X.(*ast.Ident)
		if !ok {
			continue
		}
		if pkg.Name == "game" && sel.Sel.Name == "CardDef" {
			return true
		}
	}
	return false
}
