// Code generated by gencardlist; DO NOT EDIT.

package m

import "github.com/natefinch/council4/mtg/game"

// Cards lists all card definitions in this package.
var Cards = []*game.CardDef{
	Magmaw,
	MalametBattleGlyph,
	MarthaJones,
	MasterSRebuke,
	MorbidOpportunist,
	MortalObstinacy,
	MossfireValley,
	MosswortBridge,
	Mountain,
	MrOrfeoTheBoulder,
	MurderInvestigation,
	MysticMight,
}
