// Code generated by gencardlist; DO NOT EDIT.

package m

import "github.com/natefinch/council4/mtg/game"

// Cards lists all card definitions in this package.
var Cards = []*game.CardDef{
	MaestrosTheater,
	MagmaSpray,
	Magmaroth,
	Magmaw,
	MagneticMine,
	MalakirSoothsayer,
	MalametBattleGlyph,
	ManaReflection,
	MarthaJones,
	MasterPiandao,
	MasterSRebuke,
	MeletisAstronomer,
	MemorialToUnity,
	MemoryPlunder,
	MephiticDraught,
	MesmericOrb,
	MichelangeloGameMaster,
	MilitiaBugler,
	MindSculpt,
	Mindcrank,
	MindeyeDrake,
	MindstabThrull,
	Mobilization,
	Molderhulk,
	MonumentalHenge,
	MoonveilDragon,
	MorbidOpportunist,
	MortalObstinacy,
	MossfireValley,
	MosswortBridge,
	Mountain,
	MournerSSurprise,
	MrOrfeoTheBoulder,
	MundaSVanguard,
	MurderInvestigation,
	MycosynthWellspring,
	MysticMight,
}
